_G[MAP_ELEMENT_OPPOSITES] =
	{
		[ELEMENT_FIRE] =      ELEMENT_WATER,
		[ELEMENT_ICE] =       ELEMENT_FIRE,
		[ELEMENT_WIND] =      ELEMENT_ICE,
		[ELEMENT_EARTH] =     ELEMENT_WIND,
		[ELEMENT_LIGHTNING] = ELEMENT_EARTH,
		[ELEMENT_WATER] =     ELEMENT_LIGHTNING,
		[ELEMENT_LIGHT] =     ELEMENT_DARK,
		[ELEMENT_DARK] =      ELEMENT_LIGHT
	}