_G[MAP_JA] = {
["Mighty Strikes"] = 		{id=16,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Hundred Fists"] = 		{id=17,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Benediction"] = 		{id=18,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Manafont"] = 		{id=19,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Chainspell"] = 		{id=20,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Perfect Dodge"] = 		{id=21,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Invincible"] = 		{id=22,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Blood Weapon"] = 		{id=23,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Familiar"] = 		{id=24,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Soul Voice"] = 		{id=25,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Eagle Eye Shot"] = 		{id=26,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Meikyo Shisui"] = 		{id=27,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Mijin Gakure"] = 		{id=28,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Spirit Surge"] = 		{id=29,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Astral Flow"] = 		{id=30,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Berserk"] = 		{id=31,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Warcry"] = 		{id=32,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Defender"] = 		{id=33,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Aggressor"] = 		{id=34,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Provoke"] = 		{id=35,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Focus"] = 		{id=36,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Dodge"] = 		{id=37,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Chakra"] = 		{id=38,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Boost"] = 		{id=39,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Counterstance"] = 		{id=40,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Steal"] = 		{id=41,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Flee"] = 		{id=42,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Hide"] = 		{id=43,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Sneak Attack"] = 		{id=44,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Mug"] = 		{id=45,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Shield Bash"] = 		{id=46,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Holy Circle"] = 		{id=47,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Sentinel"] = 		{id=48,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Souleater"] = 		{id=49,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Arcane Circle"] = 		{id=50,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Last Resort"] = 		{id=51,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Charm"] = 		{id=52,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Gauge"] = 		{id=53,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Tame"] = 		{id=54,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Pet commands"] = 		{id=55,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Scavenge"] = 		{id=56,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Shadowbind"] = 		{id=57,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Camouflage"] = 		{id=58,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Sharpshot"] = 		{id=59,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Barrage"] = 		{id=60,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Call Wyvern"] = 		{id=61,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Third Eye"] = 		{id=62,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Meditate"] = 		{id=63,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Warding Circle"] = 		{id=64,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Ancient Circle"] = 		{id=65,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Jump"] = 		{id=66,		ParentGroup=MAP_JA_JUMP, 		DamageType=MAP_DAMAGE_NONE},
["High Jump"] = 		{id=67,		ParentGroup=MAP_JA_JUMP, 		DamageType=MAP_DAMAGE_NONE},
["Super Jump"] = 		{id=68,		ParentGroup=MAP_JA_JUMP, 		DamageType=MAP_DAMAGE_NONE},
["Fight"] = 		{id=69,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Heel"] = 		{id=70,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Leave"] = 		{id=71,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Sic"] = 		{id=72,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Stay"] = 		{id=73,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Divine Seal"] = 		{id=74,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Elemental Seal"] = 		{id=75,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Trick Attack"] = 		{id=76,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Weapon Bash"] = 		{id=77,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Reward"] = 		{id=78,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Cover"] = 		{id=79,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Spirit Link"] = 		{id=80,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Enrage"] = 		{id=81,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Chi Blast"] = 		{id=82,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Convert"] = 		{id=83,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Accomplice"] = 		{id=84,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Call Beast"] = 		{id=85,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Unlimited Shot"] = 		{id=86,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Dismiss"] = 		{id=87,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Assault"] = 		{id=88,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Retreat"] = 		{id=89,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Release"] = 		{id=90,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Blood Pact: Rage"] = 		{id=91,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_NONE},
["Rampart"] = 		{id=92,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Azure Lore"] = 		{id=93,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Chain Affinity"] = 		{id=94,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Burst Affinity"] = 		{id=95,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Wild Card"] = 		{id=96,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Phantom Roll"] = 		{id=97,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Fighter's Roll"] = 		{id=98,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Monk's Roll"] = 		{id=99,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Healer's Roll"] = 		{id=100,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Wizard's Roll"] = 		{id=101,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Warlock's Roll"] = 		{id=102,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Rogue's Roll"] = 		{id=103,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Gallant's Roll"] = 		{id=104,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Chaos Roll"] = 		{id=105,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Beast Roll"] = 		{id=106,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Choral Roll"] = 		{id=107,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Hunter's Roll"] = 		{id=108,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Samurai Roll"] = 		{id=109,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Ninja Roll"] = 		{id=110,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Drachen Roll"] = 		{id=111,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Evoker's Roll"] = 		{id=112,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Magus's Roll"] = 		{id=113,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Corsair's Roll"] = 		{id=114,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Puppet Roll"] = 		{id=115,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Dancer's Roll"] = 		{id=116,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Scholar's Roll"] = 		{id=117,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Bolter's Roll"] = 		{id=118,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Caster's Roll"] = 		{id=119,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Courser's Roll"] = 		{id=120,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Blitzer's Roll"] = 		{id=121,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Tactician's Roll"] = 		{id=122,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Double-Up"] = 		{id=123,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Quick Draw"] = 		{id=124,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Fire Shot"] = 		{id=125,		ParentGroup=MAP_JA_CORSAIRSHOT, 		DamageType=MAP_DAMAGE_NONE},
["Ice Shot"] = 		{id=126,		ParentGroup=MAP_JA_CORSAIRSHOT, 		DamageType=MAP_DAMAGE_NONE},
["Wind Shot"] = 		{id=127,		ParentGroup=MAP_JA_CORSAIRSHOT, 		DamageType=MAP_DAMAGE_NONE},
["Earth Shot"] = 		{id=128,		ParentGroup=MAP_JA_CORSAIRSHOT, 		DamageType=MAP_DAMAGE_NONE},
["Thunder Shot"] = 		{id=129,		ParentGroup=MAP_JA_CORSAIRSHOT, 		DamageType=MAP_DAMAGE_NONE},
["Water Shot"] = 		{id=130,		ParentGroup=MAP_JA_CORSAIRSHOT, 		DamageType=MAP_DAMAGE_NONE},
["Light Shot"] = 		{id=131,		ParentGroup=MAP_JA_CORSAIRSHOT, 		DamageType=MAP_DAMAGE_NONE},
["Dark Shot"] = 		{id=132,		ParentGroup=MAP_JA_CORSAIRSHOT, 		DamageType=MAP_DAMAGE_NONE},
["Random Deal"] = 		{id=133,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Overdrive"] = 		{id=135,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Activate"] = 		{id=136,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Repair"] = 		{id=137,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Deploy"] = 		{id=138,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Deactivate"] = 		{id=139,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Retrieve"] = 		{id=140,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Fire Maneuver"] = 		{id=141,		ParentGroup=MAP_JA_MANEUVER, 		DamageType=MAP_DAMAGE_NONE},
["Ice Maneuver"] = 		{id=142,		ParentGroup=MAP_JA_MANEUVER, 		DamageType=MAP_DAMAGE_NONE},
["Wind Maneuver"] = 		{id=143,		ParentGroup=MAP_JA_MANEUVER, 		DamageType=MAP_DAMAGE_NONE},
["Earth Maneuver"] = 		{id=144,		ParentGroup=MAP_JA_MANEUVER, 		DamageType=MAP_DAMAGE_NONE},
["Thunder Maneuver"] = 		{id=145,		ParentGroup=MAP_JA_MANEUVER, 		DamageType=MAP_DAMAGE_NONE},
["Water Maneuver"] = 		{id=146,		ParentGroup=MAP_JA_MANEUVER, 		DamageType=MAP_DAMAGE_NONE},
["Light Maneuver"] = 		{id=147,		ParentGroup=MAP_JA_MANEUVER, 		DamageType=MAP_DAMAGE_NONE},
["Dark Maneuver"] = 		{id=148,		ParentGroup=MAP_JA_MANEUVER, 		DamageType=MAP_DAMAGE_NONE},
["Warrior's Charge"] = 		{id=149,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Tomahawk"] = 		{id=150,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Mantra"] = 		{id=151,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Formless Strikes"] = 		{id=152,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Martyr"] = 		{id=153,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Devotion"] = 		{id=154,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Assassin's Charge"] = 		{id=155,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Feint"] = 		{id=156,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Fealty"] = 		{id=157,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Chivalry"] = 		{id=158,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Dark Seal"] = 		{id=159,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Diabolic Eye"] = 		{id=160,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Feral Howl"] = 		{id=161,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Killer Instinct"] = 		{id=162,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Nightingale"] = 		{id=163,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Troubadour"] = 		{id=164,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Stealth Shot"] = 		{id=165,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Flashy Shot"] = 		{id=166,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Shikikoyo"] = 		{id=167,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Blade Bash"] = 		{id=168,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Deep Breathing"] = 		{id=169,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Angon"] = 		{id=170,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Sange"] = 		{id=171,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Blood Pact: Ward"] = 		{id=172,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Hasso"] = 		{id=173,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Seigan"] = 		{id=174,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Convergence"] = 		{id=175,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Diffusion"] = 		{id=176,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Snake Eye"] = 		{id=177,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Fold"] = 		{id=178,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Role Reversal"] = 		{id=179,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Ventriloquy"] = 		{id=180,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Trance"] = 		{id=181,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Sambas"] = 		{id=182,		ParentGroup=MAP_JA_SAMBA, 		DamageType=MAP_DAMAGE_NONE},
["Waltzes"] = 		{id=183,		ParentGroup=MAP_JA_WALTZ, 		DamageType=MAP_DAMAGE_NONE},
["Drain Samba"] = 		{id=184,		ParentGroup=MAP_JA_SAMBA, 		DamageType=MAP_DAMAGE_NONE},
["Drain Samba II"] = 		{id=185,		ParentGroup=MAP_JA_SAMBA, 		DamageType=MAP_DAMAGE_NONE},
["Drain Samba III"] = 		{id=186,		ParentGroup=MAP_JA_SAMBA, 		DamageType=MAP_DAMAGE_NONE},
["Aspir Samba"] = 		{id=187,		ParentGroup=MAP_JA_SAMBA, 		DamageType=MAP_DAMAGE_NONE},
["Aspir Samba II"] = 		{id=188,		ParentGroup=MAP_JA_SAMBA, 		DamageType=MAP_DAMAGE_NONE},
["Haste Samba"] = 		{id=189,		ParentGroup=MAP_JA_SAMBA, 		DamageType=MAP_DAMAGE_NONE},
["Curing Waltz"] = 		{id=190,		ParentGroup=MAP_JA_WALTZ, 		DamageType=MAP_DAMAGE_NONE},
["Curing Waltz II"] = 		{id=191,		ParentGroup=MAP_JA_WALTZ, 		DamageType=MAP_DAMAGE_NONE},
["Curing Waltz III"] = 		{id=192,		ParentGroup=MAP_JA_WALTZ, 		DamageType=MAP_DAMAGE_NONE},
["Curing Waltz IV"] = 		{id=193,		ParentGroup=MAP_JA_WALTZ, 		DamageType=MAP_DAMAGE_NONE},
["Healing Waltz"] = 		{id=194,		ParentGroup=MAP_JA_WALTZ, 		DamageType=MAP_DAMAGE_NONE},
["Divine Waltz"] = 		{id=195,		ParentGroup=MAP_JA_WALTZ, 		DamageType=MAP_DAMAGE_NONE},
["Spectral Jig"] = 		{id=196,		ParentGroup=MAP_JA_JIG, 		DamageType=MAP_DAMAGE_NONE},
["Chocobo Jig"] = 		{id=197,		ParentGroup=MAP_JA_JIG, 		DamageType=MAP_DAMAGE_NONE},
["Jigs"] = 		{id=198,		ParentGroup=MAP_JA_JIG, 		DamageType=MAP_DAMAGE_NONE},
["Steps"] = 		{id=199,		ParentGroup=MAP_JA_STEP, 		DamageType=MAP_DAMAGE_NONE},
["Flourishes I"] = 		{id=200,		ParentGroup=MAP_JA_FLOURISH, 		DamageType=MAP_DAMAGE_NONE},
["Quickstep"] = 		{id=201,		ParentGroup=MAP_JA_STEP, 		DamageType=MAP_DAMAGE_NONE},
["Box Step"] = 		{id=202,		ParentGroup=MAP_JA_STEP, 		DamageType=MAP_DAMAGE_NONE},
["Stutter Step"] = 		{id=203,		ParentGroup=MAP_JA_STEP, 		DamageType=MAP_DAMAGE_NONE},
["Animated Flourish"] = 		{id=204,		ParentGroup=MAP_JA_FLOURISH, 		DamageType=MAP_DAMAGE_NONE},
["Desperate Flourish"] = 		{id=205,		ParentGroup=MAP_JA_FLOURISH, 		DamageType=MAP_DAMAGE_NONE},
["Reverse Flourish"] = 		{id=206,		ParentGroup=MAP_JA_FLOURISH, 		DamageType=MAP_DAMAGE_NONE},
["Violent Flourish"] = 		{id=207,		ParentGroup=MAP_JA_FLOURISH, 		DamageType=MAP_DAMAGE_NONE},
["Building Flourish"] = 		{id=208,		ParentGroup=MAP_JA_FLOURISH, 		DamageType=MAP_DAMAGE_NONE},
["Wild Flourish"] = 		{id=209,		ParentGroup=MAP_JA_FLOURISH, 		DamageType=MAP_DAMAGE_NONE},
["Tabula Rasa"] = 		{id=210,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Light Arts"] = 		{id=211,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Dark Arts"] = 		{id=212,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Flourishes II"] = 		{id=213,		ParentGroup=MAP_JA_FLOURISH, 		DamageType=MAP_DAMAGE_NONE},
["Modus Veritas"] = 		{id=214,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Penury"] = 		{id=215,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Celerity"] = 		{id=216,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Rapture"] = 		{id=217,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Accession"] = 		{id=218,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Parsimony"] = 		{id=219,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Alacrity"] = 		{id=220,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Ebullience"] = 		{id=221,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Manifestation"] = 		{id=222,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Stratagems"] = 		{id=223,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Velocity Shot"] = 		{id=224,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Snarl"] = 		{id=225,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Retaliation"] = 		{id=226,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Footwork"] = 		{id=227,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Despoil"] = 		{id=228,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Pianissimo"] = 		{id=229,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Sekkanoki"] = 		{id=230,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Elemental Siphon"] = 		{id=232,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Sublimation"] = 		{id=233,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Addendum: White"] = 		{id=234,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Addendum: Black"] = 		{id=235,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Collaborator"] = 		{id=236,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Saber Dance"] = 		{id=237,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Fan Dance"] = 		{id=238,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["No Foot Rise"] = 		{id=239,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Altruism"] = 		{id=240,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Focalization"] = 		{id=241,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Tranquility"] = 		{id=242,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Equanimity"] = 		{id=243,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Enlightenment"] = 		{id=244,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Afflatus Solace"] = 		{id=245,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Afflatus Misery"] = 		{id=246,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Composure"] = 		{id=247,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Yonin"] = 		{id=248,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Innin"] = 		{id=249,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Avatar's Favor"] = 		{id=250,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Ready"] = 		{id=251,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Restraint"] = 		{id=252,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Perfect Counter"] = 		{id=253,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Mana Wall"] = 		{id=254,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Divine Emblem"] = 		{id=255,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Nether Void"] = 		{id=256,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Double Shot"] = 		{id=257,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Sengikori"] = 		{id=258,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Futae"] = 		{id=259,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Spirit Jump"] = 		{id=260,		ParentGroup=MAP_JA_JUMP, 		DamageType=MAP_DAMAGE_NONE},
["Presto"] = 		{id=261,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Divine Waltz II"] = 		{id=262,		ParentGroup=MAP_JA_WALTZ, 		DamageType=MAP_DAMAGE_NONE},
["Flourishes III"] = 		{id=263,		ParentGroup=MAP_JA_FLOURISH, 		DamageType=MAP_DAMAGE_NONE},
["Climactic Flourish"] = 		{id=264,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Libra"] = 		{id=265,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Tactical Switch"] = 		{id=266,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Blood Rage"] = 		{id=267,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Impetus"] = 		{id=269,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Divine Caress"] = 		{id=270,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Sacrosanctity"] = 		{id=271,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Enmity Douse"] = 		{id=272,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Manawell"] = 		{id=273,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Saboteur"] = 		{id=274,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Spontaneity"] = 		{id=275,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Conspirator"] = 		{id=276,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Sepulcher"] = 		{id=277,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Palisade"] = 		{id=278,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Arcane Crest"] = 		{id=279,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Scarlet Delirium"] = 		{id=280,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Spur"] = 		{id=281,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Run Wild"] = 		{id=282,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Tenuto"] = 		{id=283,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Marcato"] = 		{id=284,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Bounty Shot"] = 		{id=285,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Decoy Shot"] = 		{id=286,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Hamanoha"] = 		{id=287,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Hagakure"] = 		{id=288,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Issekigan"] = 		{id=291,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Dragon Breaker"] = 		{id=292,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Soul Jump"] = 		{id=293,		ParentGroup=MAP_JA_JUMP, 		DamageType=MAP_DAMAGE_NONE},
["Steady Wing"] = 		{id=295,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Mana Cede"] = 		{id=296,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Efflux"] = 		{id=297,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Unbridled Learning"] = 		{id=298,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Triple Shot"] = 		{id=301,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Allies' Roll"] = 		{id=302,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Miser's Roll"] = 		{id=303,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Companion's Roll"] = 		{id=304,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Avenger's Roll"] = 		{id=305,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Cooldown"] = 		{id=309,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Deus Ex Automata"] = 		{id=310,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Curing Waltz V"] = 		{id=311,		ParentGroup=MAP_JA_WALTZ, 		DamageType=MAP_DAMAGE_NONE},
["Feather Step"] = 		{id=312,		ParentGroup=MAP_JA_STEP, 		DamageType=MAP_DAMAGE_NONE},
["Striking Flourish"] = 		{id=313,		ParentGroup=MAP_JA_FLOURISH, 		DamageType=MAP_DAMAGE_NONE},
["Ternary Flourish"] = 		{id=314,		ParentGroup=MAP_JA_FLOURISH, 		DamageType=MAP_DAMAGE_NONE},
["Perpetuance"] = 		{id=316,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Immanence"] = 		{id=317,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Smiting Breath"] = 		{id=318,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Restoring Breath"] = 		{id=319,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Konzen-ittai"] = 		{id=320,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Bully"] = 		{id=321,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Maintenance"] = 		{id=322,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Brazen Rush"] = 		{id=323,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Inner Strength"] = 		{id=324,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Asylum"] = 		{id=325,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Subtle Sorcery"] = 		{id=326,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Stymie"] = 		{id=327,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Larceny"] = 		{id=328,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Intervene"] = 		{id=329,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Soul Enslavement"] = 		{id=330,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Unleash"] = 		{id=331,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Clarion Call"] = 		{id=332,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Overkill"] = 		{id=333,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Yaegasumi"] = 		{id=334,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Mikage"] = 		{id=335,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Fly High"] = 		{id=336,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Astral Conduit"] = 		{id=337,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Unbridled Wisdom"] = 		{id=338,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Cutting Cards"] = 		{id=339,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Heady Artifice"] = 		{id=340,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Grand Pas"] = 		{id=341,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Caper Emissarius"] = 		{id=342,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Bolster"] = 		{id=343,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Swipe"] = 		{id=344,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Full Circle"] = 		{id=345,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Lasting Emanation"] = 		{id=346,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Ecliptic Attrition"] = 		{id=347,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Collimated Fervor"] = 		{id=348,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Life Cycle"] = 		{id=349,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Blaze of Glory"] = 		{id=350,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Dematerialize"] = 		{id=351,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Theurgic Focus"] = 		{id=352,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Concentric Pulse"] = 		{id=353,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Mending Halation"] = 		{id=354,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Radial Arcana"] = 		{id=355,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Elemental Sforzo"] = 		{id=356,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Rune Enchantment"] = 		{id=357,		ParentGroup=MAP_JA_RUNE, 		DamageType=MAP_DAMAGE_NONE},
["Ignis"] = 		{id=358,		ParentGroup=MAP_JA_RUNE, 		DamageType=MAP_DAMAGE_NONE},
["Gelus"] = 		{id=359,		ParentGroup=MAP_JA_RUNE, 		DamageType=MAP_DAMAGE_NONE},
["Flabra"] = 		{id=360,		ParentGroup=MAP_JA_RUNE, 		DamageType=MAP_DAMAGE_NONE},
["Tellus"] = 		{id=361,		ParentGroup=MAP_JA_RUNE, 		DamageType=MAP_DAMAGE_NONE},
["Sulpor"] = 		{id=362,		ParentGroup=MAP_JA_RUNE, 		DamageType=MAP_DAMAGE_NONE},
["Unda"] = 		{id=363,		ParentGroup=MAP_JA_RUNE, 		DamageType=MAP_DAMAGE_NONE},
["Lux"] = 		{id=364,		ParentGroup=MAP_JA_RUNE, 		DamageType=MAP_DAMAGE_NONE},
["Tenebrae"] = 		{id=365,		ParentGroup=MAP_JA_RUNE, 		DamageType=MAP_DAMAGE_NONE},
["Vallation"] = 		{id=366,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Swordplay"] = 		{id=367,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Lunge"] = 		{id=368,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Pflug"] = 		{id=369,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Embolden"] = 		{id=370,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Valiance"] = 		{id=371,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Gambit"] = 		{id=372,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Liement"] = 		{id=373,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["One for All"] = 		{id=374,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Rayke"] = 		{id=375,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Battuta"] = 		{id=376,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Widened Compass"] = 		{id=377,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Odyllic Subterfuge"] = 		{id=378,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Ward"] = 		{id=379,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Effusion"] = 		{id=380,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Chocobo Jig II"] = 		{id=381,		ParentGroup=MAP_JA_JIG, 		DamageType=MAP_DAMAGE_NONE},
["Relinquish"] = 		{id=382,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Vivacious Pulse"] = 		{id=383,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Contradance"] = 		{id=384,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Apogee"] = 		{id=385,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Entrust"] = 		{id=386,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Bestial Loyalty"] = 		{id=387,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Cascade"] = 		{id=388,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Consume Mana"] = 		{id=389,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Naturalist's Roll"] = 		{id=390,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Runeist's Roll"] = 		{id=391,		ParentGroup=MAP_JA_ROLL, 		DamageType=MAP_DAMAGE_NONE},
["Crooked Cards"] = 		{id=392,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Spirit Bond"] = 		{id=393,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Majesty"] = 		{id=394,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Hover Shot"] = 		{id=395,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Healing Ruby"] = 		{id=512,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Poison Nails"] = 		{id=513,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Shining Ruby"] = 		{id=514,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Glittering Ruby"] = 		{id=515,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Meteorite"] = 		{id=516,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Healing Ruby II"] = 		{id=517,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Searing Light"] = 		{id=518,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Holy Mist"] = 		{id=519,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Soothing Ruby"] = 		{id=520,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Regal Scratch"] = 		{id=521,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Mewing Lullaby"] = 		{id=522,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Eerie Eye"] = 		{id=523,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Level ? Holy"] = 		{id=524,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Raise II"] = 		{id=525,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Reraise II"] = 		{id=526,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Altana's Favor"] = 		{id=527,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Moonlit Charge"] = 		{id=528,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Crescent Fang"] = 		{id=529,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Lunar Cry"] = 		{id=530,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Lunar Roar"] = 		{id=531,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Ecliptic Growl"] = 		{id=532,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Ecliptic Howl"] = 		{id=533,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Eclipse Bite"] = 		{id=534,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Howling Moon"] = 		{id=536,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Lunar Bay"] = 		{id=537,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Heavenward Howl"] = 		{id=538,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Impact"] = 		{id=539,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Punch"] = 		{id=544,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Fire II"] = 		{id=545,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Burning Strike"] = 		{id=546,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_HYBRID},
["Double Punch"] = 		{id=547,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Crimson Howl"] = 		{id=548,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Fire IV"] = 		{id=549,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Flaming Crush"] = 		{id=550,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_HYBRID},
["Meteor Strike"] = 		{id=551,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Inferno"] = 		{id=552,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Inferno Howl"] = 		{id=553,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Conflag Strike"] = 		{id=554,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Rock Throw"] = 		{id=560,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Stone II"] = 		{id=561,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Rock Buster"] = 		{id=562,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Megalith Throw"] = 		{id=563,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Earthen Ward"] = 		{id=564,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Stone IV"] = 		{id=565,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Mountain Buster"] = 		{id=566,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Geocrush"] = 		{id=567,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Earthen Fury"] = 		{id=568,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Earthen Armor"] = 		{id=569,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Crag Throw"] = 		{id=570,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Barracuda Dive"] = 		{id=576,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Water II"] = 		{id=577,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Tail Whip"] = 		{id=578,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Spring Water"] = 		{id=579,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Slowga"] = 		{id=580,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Water IV"] = 		{id=581,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Spinning Dive"] = 		{id=582,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Grand Fall"] = 		{id=583,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Tidal Wave"] = 		{id=584,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Tidal Roar"] = 		{id=585,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Soothing Current"] = 		{id=586,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Claw"] = 		{id=592,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Aero II"] = 		{id=593,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Whispering Wind"] = 		{id=594,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Hastega"] = 		{id=595,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Aerial Armor"] = 		{id=596,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Aero IV"] = 		{id=597,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Predator Claws"] = 		{id=598,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Wind Blade"] = 		{id=599,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Aerial Blast"] = 		{id=600,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Fleet Wind"] = 		{id=601,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Hastega II"] = 		{id=602,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Axe Kick"] = 		{id=608,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Blizzard II"] = 		{id=609,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Frost Armor"] = 		{id=610,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Sleepga"] = 		{id=611,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Double Slap"] = 		{id=612,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Blizzard IV"] = 		{id=613,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Rush"] = 		{id=614,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Heavenly Strike"] = 		{id=615,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Diamond Dust"] = 		{id=616,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Diamond Storm"] = 		{id=617,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Crystal Blessing"] = 		{id=618,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Shock Strike"] = 		{id=624,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Thunder II"] = 		{id=625,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Rolling Thunder"] = 		{id=626,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Thunderspark"] = 		{id=627,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Lightning Armor"] = 		{id=628,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Thunder IV"] = 		{id=629,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Chaotic Strike"] = 		{id=630,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Thunderstorm"] = 		{id=631,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Judgment Bolt"] = 		{id=632,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Shock Squall"] = 		{id=633,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Volt Strike"] = 		{id=634,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Healing Breath IV"] = 		{id=639,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Healing Breath"] = 		{id=640,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Healing Breath II"] = 		{id=641,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Healing Breath III"] = 		{id=642,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Remove Poison"] = 		{id=643,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Remove Blindness"] = 		{id=644,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Remove Paralysis"] = 		{id=645,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Flame Breath"] = 		{id=646,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Frost Breath"] = 		{id=647,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Gust Breath"] = 		{id=648,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Sand Breath"] = 		{id=649,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Lightning Breath"] = 		{id=650,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Hydro Breath"] = 		{id=651,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Super Climb"] = 		{id=652,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Remove Curse"] = 		{id=653,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Remove Disease"] = 		{id=654,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Camisado"] = 		{id=656,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Somnolence"] = 		{id=657,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Nightmare"] = 		{id=658,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Ultimate Terror"] = 		{id=659,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Noctoshield"] = 		{id=660,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Dream Shroud"] = 		{id=661,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Nether Blast"] = 		{id=662,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Cacodemonia"] = 		{id=663,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Ruinous Omen"] = 		{id=664,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Night Terror"] = 		{id=665,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Pavor Nocturnus"] = 		{id=666,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Blindside"] = 		{id=667,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Deconstruction"] = 		{id=668,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Chronoshift"] = 		{id=669,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Zantetsuken"] = 		{id=670,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Perfect Defense"] = 		{id=671,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Foot Kick"] = 		{id=672,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Dust Cloud"] = 		{id=673,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Whirl Claws"] = 		{id=674,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Head Butt"] = 		{id=675,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Dream Flower"] = 		{id=676,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Wild Oats"] = 		{id=677,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Leaf Dagger"] = 		{id=678,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Scream"] = 		{id=679,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Roar"] = 		{id=680,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Razor Fang"] = 		{id=681,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Claw Cyclone"] = 		{id=682,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Tail Blow"] = 		{id=683,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Fireball"] = 		{id=684,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Blockhead"] = 		{id=685,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Brain Crush"] = 		{id=686,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Infrasonics"] = 		{id=687,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Secretion"] = 		{id=688,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Lamb Chop"] = 		{id=689,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Rage"] = 		{id=690,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Sheep Charge"] = 		{id=691,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Sheep Song"] = 		{id=692,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Bubble Shower"] = 		{id=693,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Bubble Curtain"] = 		{id=694,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Big Scissors"] = 		{id=695,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Scissor Guard"] = 		{id=696,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Metallic Body"] = 		{id=697,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Needleshot"] = 		{id=698,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["??? Needles"] = 		{id=699,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Frogkick"] = 		{id=700,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Spore"] = 		{id=701,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Queasyshroom"] = 		{id=702,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Numbshroom"] = 		{id=703,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Shakeshroom"] = 		{id=704,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Silence Gas"] = 		{id=705,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Dark Spore"] = 		{id=706,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Power Attack"] = 		{id=707,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Hi-Freq Field"] = 		{id=708,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Rhino Attack"] = 		{id=709,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Rhino Guard"] = 		{id=710,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Spoil"] = 		{id=711,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Cursed Sphere"] = 		{id=712,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Venom"] = 		{id=713,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Sandblast"] = 		{id=714,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Sandpit"] = 		{id=715,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Venom Spray"] = 		{id=716,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Mandibular Bite"] = 		{id=717,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Soporific"] = 		{id=718,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Gloeosuccus"] = 		{id=719,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Palsy Pollen"] = 		{id=720,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Geist Wall"] = 		{id=721,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Numbing Noise"] = 		{id=722,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Nimble Snap"] = 		{id=723,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Cyclotail"] = 		{id=724,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Toxic Spit"] = 		{id=725,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Double Claw"] = 		{id=726,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Grapple"] = 		{id=727,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Spinning Top"] = 		{id=728,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Filamented Hold"] = 		{id=729,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Chaotic Eye"] = 		{id=730,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Blaster"] = 		{id=731,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Suction"] = 		{id=732,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Drainkiss"] = 		{id=733,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Snow Cloud"] = 		{id=734,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Wild Carrot"] = 		{id=735,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Sudden Lunge"] = 		{id=736,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Spiral Spin"] = 		{id=737,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Noisome Powder"] = 		{id=738,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Acid Mist"] = 		{id=740,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["TP Drainkiss"] = 		{id=741,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Scythe Tail"] = 		{id=743,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Ripper Fang"] = 		{id=744,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Chomp Rush"] = 		{id=745,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Charged Whisker"] = 		{id=746,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Purulent Ooze"] = 		{id=747,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Corrosive Ooze"] = 		{id=748,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Back Heel"] = 		{id=749,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Jettatura"] = 		{id=750,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Choke Breath"] = 		{id=751,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Fantod"] = 		{id=752,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Tortoise Stomp"] = 		{id=753,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Harden Shell"] = 		{id=754,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Aqua Breath"] = 		{id=755,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Wing Slap"] = 		{id=756,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Beak Lunge"] = 		{id=757,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Intimidate"] = 		{id=758,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Recoil Dive"] = 		{id=759,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Water Wall"] = 		{id=760,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Sensilla Blades"] = 		{id=761,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Tegmina Buffet"] = 		{id=762,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Molting Plumage"] = 		{id=763,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Swooping Frenzy"] = 		{id=764,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Sweeping Gouge"] = 		{id=765,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Zealous Snort"] = 		{id=766,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Pentapeck"] = 		{id=767,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Tickling Tendrils"] = 		{id=768,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Stink Bomb"] = 		{id=769,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Nectarous Deluge"] = 		{id=770,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Nepenthic Plunge"] = 		{id=771,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Somersault"] = 		{id=772,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Pacifying Ruby"] = 		{id=773,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Foul Waters"] = 		{id=774,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Pestilent Plume"] = 		{id=775,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Pecking Flurry"] = 		{id=776,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Sickle Slash"] = 		{id=777,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Acid Spray"] = 		{id=778,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Spider Web"] = 		{id=779,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Regal Gash"] = 		{id=780,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Infected Leech"] = 		{id=781,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Gloom Spray"] = 		{id=782,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Disembowel"] = 		{id=786,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Extirpating Salvo"] = 		{id=787,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Venom Shower"] = 		{id=788,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Mega Scissors"] = 		{id=789,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Frenzied Rage"] = 		{id=790,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Rhinowrecker"] = 		{id=791,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Fluid Toss"] = 		{id=792,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Fluid Spread"] = 		{id=793,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Digest"] = 		{id=794,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_MAGICAL},
["Crossthrash"] = 		{id=795,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Predatory Glare"] = 		{id=796,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Hoof Volley"] = 		{id=797,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Nihility Song"] = 		{id=798,		ParentGroup=MAP_JA_READY, 		DamageType=MAP_DAMAGE_NONE},
["Clarsach Call"] = 		{id=960,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Welt"] = 		{id=961,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Katabatic Blades"] = 		{id=962,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Lunatic Voice"] = 		{id=963,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Roundhouse"] = 		{id=964,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL},
["Chinook"] = 		{id=965,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Bitter Elegy"] = 		{id=966,		ParentGroup=MAP_JA_BLOODPACT_WARD, 		DamageType=MAP_DAMAGE_NONE},
["Sonic Buffet"] = 		{id=967,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Tornado II"] = 		{id=968,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_MAGICAL},
["Wind's Blessing"] = 		{id=969,		ParentGroup=MAP_JA_DEFAULT, 		DamageType=MAP_DAMAGE_NONE},
["Hysteric Assault"] = 		{id=970,		ParentGroup=MAP_JA_BLOODPACT_RAGE, 		DamageType=MAP_DAMAGE_PHYSICAL}
}