_G[MAP_SKILLS]= {
	["(N/A)"]=					{id=0, shortname=MAP_SKILL_OTHER},
	["Hand-to-Hand"]=			{id=1, shortname="Hand-to-Hand"},
	["Dagger"]=					{id=2, shortname="Dagger"},
	["Sword"]= 					{id=3, shortname="Sword"},
	["Great Sword"]= 			{id=4, shortname="Great Sword"},
	["Axe"]= 					{id=5, shortname="Axe"},
	["Great Axe"]= 				{id=6, shortname="Great Axe"},
	["Scythe"]= 				{id=7, shortname="Scythe"},
	["Polearm"]= 				{id=8, shortname="Polearm"},
	["Katana"]= 				{id=9, shortname="Katana"},
	["Great Katana"]= 			{id=10, shortname="Great Katana"},
	["Club"]= 					{id=11, shortname="Club"},
	["Staff"]= 					{id=12, shortname="Staff"},
	["Automaton Melee"]=		{id=22, shortname=MAP_SKILL_AUTO_MELEE},
	["Automaton Archery"]= 		{id=23, shortname=MAP_SKILL_AUTO_ARCHERY},
	["Automaton Magic"]=		{id=24, shortname=MAP_SKILL_AUTO_MAGIC},
	["Divine Magic"]= 			{id=32, shortname=MAP_SKILL_DIVINE},
	["Healing Magic"]= 			{id=33, shortname=MAP_SKILL_HEALING},
	["Enhancing Magic"]=		{id=34, shortname=MAP_SKILL_ENHANCING},
	["Enfeebling Magic"]=		{id=35, shortname=MAP_SKILL_ENFEEBLING},
	["Elemental Magic"]=		{id=36, shortname=MAP_SKILL_ELEMENTAL},
	["Dark Magic"]=				{id=37, shortname=MAP_SKILL_DARK},
	["Summoning Magic"]=		{id=38, shortname=MAP_SKILL_SUMMONING},
	["Ninjutsu"]=				{id=39, shortname=MAP_SKILL_NINJUTSU},
	["Singing"]=				{id=40, shortname=MAP_SKILL_SINGING},
	["Stringed Instrument"]= 	{id=41, shortname=MAP_SKILL_STRINGED},
	["Wind Instrument"]= 		{id=42, shortname=MAP_SKILL_WIND},
	["Blue Magic"]= 			{id=43, shortname=MAP_SKILL_BLUE},
	["Geomancy"]= 				{id=44, shortname=MAP_SKILL_GEOMANCY},
	["Handbell"]= 				{id=45, shortname=MAP_SKILL_HANDBELL},
	["Fishing"]= 				{id=48, shortname="Fishing"},
	["Woodworking"]= 			{id=49, shortname="Woodworking"},
	["Smithing"]= 				{id=50, shortname="Smithing"},
	["Goldsmithing"]= 			{id=51, shortname="Goldsmithing"},
	["Clothcraft"]= 			{id=52, shortname="Clothcraft"},
	["Leathercraft"]= 			{id=53, shortname="Leathercraft"},
	["Bonecraft"]= 				{id=54, shortname="Bonecraft"},
	["Alchemy"]= 				{id=55, shortname="Alchemy"},
	["Cooking"]= 				{id=56, shortname="Cooking"},
	["Synergy"]= 				{id=57, shortname="Synergy"}
}