_G[MAP_SPELLS] = {
	["Cure"]=			{id=1,		ParentGroup=MAP_SPELL_CURE},
	["Cure II"]=		{id=2,		ParentGroup=MAP_SPELL_CURE},
	["Cure III"]=		{id=3,		ParentGroup=MAP_SPELL_CURE},
	["Cure IV"]=		{id=4,		ParentGroup=MAP_SPELL_CURE},
	["Cure V"]=			{id=5,		ParentGroup=MAP_SPELL_CURE},
	["Cure VI"]=		{id=6,		ParentGroup=MAP_SPELL_CURE},
	["Curaga"]=			{id=7,		ParentGroup=MAP_SPELL_CURAGA},
	["Curaga II"]=		{id=8,		ParentGroup=MAP_SPELL_CURAGA},
	["Curaga III"]=		{id=9,		ParentGroup=MAP_SPELL_CURAGA},
	["Curaga IV"]=		{id=10,		ParentGroup=MAP_SPELL_CURAGA},
	["Curaga V"]=		{id=11,		ParentGroup=MAP_SPELL_CURAGA},
	["Raise"]=			{id=12,		ParentGroup=MAP_SPELL_RAISE},
	["Raise II"]=		{id=13,		ParentGroup=MAP_SPELL_RAISE},
	["Poisona"]=		{id=14,		ParentGroup=MAP_SPELL_STATUSREMOVAL},
	["Paralyna"]=		{id=15,		ParentGroup=MAP_SPELL_STATUSREMOVAL},
	["Blindna"]=		{id=16,		ParentGroup=MAP_SPELL_STATUSREMOVAL},
	["Silena"]=			{id=17,		ParentGroup=MAP_SPELL_STATUSREMOVAL},
	["Stona"]=			{id=18,		ParentGroup=MAP_SPELL_STATUSREMOVAL},
	["Viruna"]=			{id=19,		ParentGroup=MAP_SPELL_STATUSREMOVAL},
	["Cursna"]=			{id=20,		ParentGroup=MAP_SPELL_STATUSREMOVAL},
	["Holy"]=			{id=21,		ParentGroup=MAP_SPELL_HOLY},
	["Holy II"]=		{id=22,		ParentGroup=MAP_SPELL_HOLY},
	["Dia"]=			{id=23,		ParentGroup=MAP_SPELL_DIA},
	["Dia II"]=			{id=24,		ParentGroup=MAP_SPELL_DIA},
	["Dia III"]=		{id=25,		ParentGroup=MAP_SPELL_DIA},
	["Dia IV"]=			{id=26,		ParentGroup=MAP_SPELL_DIA},
	["Dia V"]=			{id=27,		ParentGroup=MAP_SPELL_DIA},
	["Banish"]=			{id=28,		ParentGroup=MAP_SPELL_BANISH},
	["Banish II"]=		{id=29,		ParentGroup=MAP_SPELL_BANISH},
	["Banish III"]=		{id=30,		ParentGroup=MAP_SPELL_BANISH},
	["Banish IV"]=		{id=31,		ParentGroup=MAP_SPELL_BANISH},
	["Banish V"]=		{id=32,		ParentGroup=MAP_SPELL_BANISH},
	["Diaga"]=			{id=33,		ParentGroup=MAP_SPELL_DIA},
	["Diaga II"]=		{id=34,		ParentGroup=MAP_SPELL_DIA},
	["Diaga III"]=		{id=35,		ParentGroup=MAP_SPELL_DIA},
	["Diaga IV"]=		{id=36,		ParentGroup=MAP_SPELL_DIA},
	["Diaga V"]=		{id=37,		ParentGroup=MAP_SPELL_DIA},
	["Banishga"]=		{id=38,		ParentGroup=MAP_SPELL_BANISH},
	["Banishga II"]=	{id=39,		ParentGroup=MAP_SPELL_BANISH},
	["Banishga III"]=	{id=40,		ParentGroup=MAP_SPELL_BANISH},
	["Banishga IV"]=	{id=41,		ParentGroup=MAP_SPELL_BANISH},
	["Banishga V"]=		{id=42,		ParentGroup=MAP_SPELL_BANISH},
	["Protect"]=		{id=43,		ParentGroup=MAP_SPELL_PROTECT},
	["Protect II"]=		{id=44,		ParentGroup=MAP_SPELL_PROTECT},
	["Protect III"]=	{id=45,		ParentGroup=MAP_SPELL_PROTECT},
	["Protect IV"]=		{id=46,		ParentGroup=MAP_SPELL_PROTECT},
	["Protect V"]=		{id=47,		ParentGroup=MAP_SPELL_PROTECT},
	["Shell"]=			{id=48,		ParentGroup=MAP_SPELL_SHELL},
	["Shell II"]=		{id=49,		ParentGroup=MAP_SPELL_SHELL},
	["Shell III"]=		{id=50,		ParentGroup=MAP_SPELL_SHELL},
	["Shell IV"]=		{id=51,		ParentGroup=MAP_SPELL_SHELL},
	["Shell V"]=		{id=52,		ParentGroup=MAP_SPELL_SHELL},
	["Blink"]=			{id=53,		ParentGroup=MAP_SPELL_DEFAULT},
	["Stoneskin"]=		{id=54,		ParentGroup=MAP_SPELL_DEFAULT},
	["Aquaveil"]=		{id=55,		ParentGroup=MAP_SPELL_DEFAULT},
	["Slow"]=			{id=56,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Haste"]=			{id=57,		ParentGroup=MAP_SPELL_HASTE},
	["Paralyze"]=		{id=58,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Silence"]=		{id=59,		ParentGroup=MAP_ENFEEBLE_DURATION},
	["Barfire"]=		{id=60,		ParentGroup=MAP_SPELL_BARELEMENT},
	["Barblizzard"]=	{id=61,		ParentGroup=MAP_SPELL_BARELEMENT},
	["Baraero"]=		{id=62,		ParentGroup=MAP_SPELL_BARELEMENT},
	["Barstone"]=		{id=63,		ParentGroup=MAP_SPELL_BARELEMENT},
	["Barthunder"]=		{id=64,		ParentGroup=MAP_SPELL_BARELEMENT},
	["Barwater"]=		{id=65,		ParentGroup=MAP_SPELL_BARELEMENT},
	["Barfira"]=		{id=66,		ParentGroup=MAP_SPELL_BARELEMENT},
	["Barblizzara"]=	{id=67,		ParentGroup=MAP_SPELL_BARELEMENT},
	["Baraera"]=		{id=68,		ParentGroup=MAP_SPELL_BARELEMENT},
	["Barstonra"]=		{id=69,		ParentGroup=MAP_SPELL_BARELEMENT},
	["Barthundra"]=		{id=70,		ParentGroup=MAP_SPELL_BARELEMENT},
	["Barwatera"]=		{id=71,		ParentGroup=MAP_SPELL_BARELEMENT},
	["Barsleep"]=		{id=72,		ParentGroup=MAP_SPELL_BARSTATUS},
	["Barpoison"]=		{id=73,		ParentGroup=MAP_SPELL_BARSTATUS},
	["Barparalyze"]=	{id=74,		ParentGroup=MAP_SPELL_BARSTATUS},
	["Barblind"]=		{id=75,		ParentGroup=MAP_SPELL_BARSTATUS},
	["Barsilence"]=		{id=76,		ParentGroup=MAP_SPELL_BARSTATUS},
	["Barpetrify"]=		{id=77,		ParentGroup=MAP_SPELL_BARSTATUS},
	["Barvirus"]=		{id=78,		ParentGroup=MAP_SPELL_BARSTATUS},
	["Slow II"]=		{id=79,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Paralyze II"]=	{id=80,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Recall-Jugner"]=	{id=81,		ParentGroup=MAP_SPELL_TELEPORT},
	["Recall-Pashh"]=	{id=82,		ParentGroup=MAP_SPELL_TELEPORT},
	["Recall-Meriph"]=	{id=83,		ParentGroup=MAP_SPELL_TELEPORT},
	["Baramnesia"]=		{id=84,		ParentGroup=MAP_SPELL_BARSTATUS},
	["Baramnesra"]=		{id=85,		ParentGroup=MAP_SPELL_BARSTATUS},
	["Barsleepra"]=		{id=86,		ParentGroup=MAP_SPELL_BARSTATUS},
	["Barpoisonra"]=	{id=87,		ParentGroup=MAP_SPELL_BARSTATUS},
	["Barparalyzra"]=	{id=88,		ParentGroup=MAP_SPELL_BARSTATUS},
	["Barblindra"]=		{id=89,		ParentGroup=MAP_SPELL_BARSTATUS},
	["Barsilencera"]=	{id=90,		ParentGroup=MAP_SPELL_BARSTATUS},
	["Barpetra"]=		{id=91,		ParentGroup=MAP_SPELL_BARSTATUS},
	["Barvira"]=		{id=92,		ParentGroup=MAP_SPELL_BARSTATUS},
	["Cura"]=			{id=93,		ParentGroup=MAP_SPELL_CURAGA},
	["Sacrifice"]=		{id=94,		ParentGroup=MAP_SPELL_DEFAULT},
	["Esuna"]=			{id=95,		ParentGroup=MAP_SPELL_DEFAULT},
	["Auspice"]=		{id=96,		ParentGroup=MAP_SPELL_DEFAULT},
	["Reprisal"]=		{id=97,		ParentGroup=MAP_SPELL_DEFAULT},
	["Repose"]=			{id=98,		ParentGroup=MAP_SPELL_DEFAULT},
	["Sandstorm"]=		{id=99,		ParentGroup=MAP_SPELL_STORM},
	["Enfire"]=			{id=100,	ParentGroup=MAP_SPELL_ENSPELL1},
	["Enblizzard"]=		{id=101,	ParentGroup=MAP_SPELL_ENSPELL1},
	["Enaero"]=			{id=102,	ParentGroup=MAP_SPELL_ENSPELL1},
	["Enstone"]=		{id=103,	ParentGroup=MAP_SPELL_ENSPELL1},
	["Enthunder"]=		{id=104,	ParentGroup=MAP_SPELL_ENSPELL1},
	["Enwater"]=		{id=105,	ParentGroup=MAP_SPELL_ENSPELL1},
	["Phalanx"]=		{id=106,	ParentGroup=MAP_SPELL_PHALANX},
	["Phalanx II"]=		{id=107,	ParentGroup=MAP_SPELL_PHALANX},
	["Regen"]=			{id=108,	ParentGroup=MAP_SPELL_REGEN},
	["Refresh"]=		{id=109,	ParentGroup=MAP_SPELL_REFRESH},
	["Regen II"]=		{id=110,	ParentGroup=MAP_SPELL_REGEN},
	["Regen III"]=		{id=111,	ParentGroup=MAP_SPELL_REGEN},
	["Flash"]=			{id=112,		ParentGroup=MAP_SPELL_STORM},
	["Rainstorm"]=		{id=113,		ParentGroup=MAP_SPELL_STORM},
	["Windstorm"]=		{id=114,		ParentGroup=MAP_SPELL_STORM},
	["Firestorm"]=		{id=115,		ParentGroup=MAP_SPELL_STORM},
	["Hailstorm"]=		{id=116,		ParentGroup=MAP_SPELL_STORM},
	["Thunderstorm"]=	{id=117,		ParentGroup=MAP_SPELL_STORM},
	["Voidstorm"]=		{id=118,		ParentGroup=MAP_SPELL_STORM},
	["Aurorastorm"]=	{id=119,		ParentGroup=MAP_SPELL_STORM},
	["Teleport-Yhoat"]=	{id=120,		ParentGroup=MAP_SPELL_TELEPORT},
	["Teleport-Altep"]=	{id=121,		ParentGroup=MAP_SPELL_TELEPORT},
	["Teleport-Holla"]=	{id=122,		ParentGroup=MAP_SPELL_TELEPORT},
	["Teleport-Dem"]=	{id=123,		ParentGroup=MAP_SPELL_TELEPORT},
	["Teleport-Mea"]=	{id=124,		ParentGroup=MAP_SPELL_TELEPORT},
	["Protectra"]=		{id=125,		ParentGroup=MAP_SPELL_PROTECT},
	["Protectra II"]=	{id=126,		ParentGroup=MAP_SPELL_PROTECT},
	["Protectra III"]=	{id=127,		ParentGroup=MAP_SPELL_PROTECT},
	["Protectra IV"]=	{id=128,		ParentGroup=MAP_SPELL_PROTECT},
	["Protectra V"]=	{id=129,		ParentGroup=MAP_SPELL_PROTECT},
	["Shellra"]=		{id=130,		ParentGroup=MAP_SPELL_SHELL},
	["Shellra II"]=		{id=131,		ParentGroup=MAP_SPELL_SHELL},
	["Shellra III"]=	{id=132,		ParentGroup=MAP_SPELL_SHELL},
	["Shellra IV"]=		{id=133,		ParentGroup=MAP_SPELL_SHELL},
	["Shellra V"]=		{id=134,		ParentGroup=MAP_SPELL_SHELL},
	["Reraise"]=		{id=135,		ParentGroup=MAP_SPELL_RERAISE},
	["Invisible"]=		{id=136,		ParentGroup=MAP_SPELL_DEFAULT},
	["Sneak"]=			{id=137,		ParentGroup=MAP_SPELL_DEFAULT},
	["Deodorize"]=		{id=138,		ParentGroup=MAP_SPELL_DEFAULT},
	["Teleport-Vahzl"]=	{id=139,		ParentGroup=MAP_SPELL_TELEPORT},
	["Raise III"]=		{id=140,		ParentGroup=MAP_SPELL_RERAISE},
	["Reraise II"]=		{id=141,		ParentGroup=MAP_SPELL_RERAISE},
	["Reraise III"]=	{id=142,		ParentGroup=MAP_SPELL_RERAISE},
	["Erase"]=			{id=143,		ParentGroup=MAP_SPELL_DEFAULT},
	["Fire"]=			{id=144,		ParentGroup=MAP_SPELL_DEFAULT},
	["Fire II"]=		{id=145,		ParentGroup=MAP_SPELL_DEFAULT},
	["Fire III"]=		{id=146,		ParentGroup=MAP_SPELL_DEFAULT},
	["Fire IV"]=		{id=147,		ParentGroup=MAP_SPELL_DEFAULT},
	["Fire V"]=			{id=148,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blizzard"]=		{id=149,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blizzard II"]=	{id=150,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blizzard III"]=	{id=151,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blizzard IV"]=	{id=152,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blizzard V"]=		{id=153,		ParentGroup=MAP_SPELL_DEFAULT},
	["Aero"]=			{id=154,		ParentGroup=MAP_SPELL_DEFAULT},
	["Aero II"]=		{id=155,		ParentGroup=MAP_SPELL_DEFAULT},
	["Aero III"]=		{id=156,		ParentGroup=MAP_SPELL_DEFAULT},
	["Aero IV"]=		{id=157,		ParentGroup=MAP_SPELL_DEFAULT},
	["Aero V"]=			{id=158,		ParentGroup=MAP_SPELL_DEFAULT},
	["Stone"]=			{id=159,		ParentGroup=MAP_SPELL_DEFAULT},
	["Stone II"]=		{id=160,		ParentGroup=MAP_SPELL_DEFAULT},
	["Stone III"]=		{id=161,		ParentGroup=MAP_SPELL_DEFAULT},
	["Stone IV"]=		{id=162,		ParentGroup=MAP_SPELL_DEFAULT},
	["Stone V"]=		{id=163,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thunder"]=		{id=164,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thunder II"]=		{id=165,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thunder III"]=	{id=166,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thunder IV"]=		{id=167,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thunder V"]=		{id=168,		ParentGroup=MAP_SPELL_DEFAULT},
	["Water"]=			{id=169,		ParentGroup=MAP_SPELL_DEFAULT},
	["Water II"]=		{id=170,		ParentGroup=MAP_SPELL_DEFAULT},
	["Water III"]=		{id=171,		ParentGroup=MAP_SPELL_DEFAULT},
	["Water IV"]=		{id=172,		ParentGroup=MAP_SPELL_DEFAULT},
	["Water V"]=		{id=173,		ParentGroup=MAP_SPELL_DEFAULT},
	["Firaga"]=			{id=174,		ParentGroup=MAP_SPELL_DEFAULT},
	["Firaga II"]=		{id=175,		ParentGroup=MAP_SPELL_DEFAULT},
	["Firaga III"]=		{id=176,		ParentGroup=MAP_SPELL_DEFAULT},
	["Firaga IV"]=		{id=177,		ParentGroup=MAP_SPELL_DEFAULT},
	["Firaga V"]=		{id=178,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blizzaga"]=		{id=179,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blizzaga II"]=	{id=180,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blizzaga III"]=	{id=181,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blizzaga IV"]=	{id=182,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blizzaga V"]=		{id=183,		ParentGroup=MAP_SPELL_DEFAULT},
	["Aeroga"]=			{id=184,		ParentGroup=MAP_SPELL_DEFAULT},
	["Aeroga II"]=		{id=185,		ParentGroup=MAP_SPELL_DEFAULT},
	["Aeroga III"]=		{id=186,		ParentGroup=MAP_SPELL_DEFAULT},
	["Aeroga IV"]=		{id=187,		ParentGroup=MAP_SPELL_DEFAULT},
	["Aeroga V"]=		{id=188,		ParentGroup=MAP_SPELL_DEFAULT},
	["Stonega"]=		{id=189,		ParentGroup=MAP_SPELL_DEFAULT},
	["Stonega II"]=		{id=190,		ParentGroup=MAP_SPELL_DEFAULT},
	["Stonega III"]=	{id=191,		ParentGroup=MAP_SPELL_DEFAULT},
	["Stonega IV"]=		{id=192,		ParentGroup=MAP_SPELL_DEFAULT},
	["Stonega V"]=		{id=193,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thundaga"]=		{id=194,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thundaga II"]=	{id=195,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thundaga III"]=	{id=196,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thundaga IV"]=	{id=197,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thundaga V"]=		{id=198,		ParentGroup=MAP_SPELL_DEFAULT},
	["Waterga"]=		{id=199,		ParentGroup=MAP_SPELL_DEFAULT},
	["Waterga II"]=		{id=200,		ParentGroup=MAP_SPELL_DEFAULT},
	["Waterga III"]=	{id=201,		ParentGroup=MAP_SPELL_DEFAULT},
	["Waterga IV"]=		{id=202,		ParentGroup=MAP_SPELL_DEFAULT},
	["Waterga V"]=		{id=203,		ParentGroup=MAP_SPELL_DEFAULT},
	["Flare"]=			{id=204,		ParentGroup=MAP_SPELL_ANCIENT},
	["Flare II"]=		{id=205,		ParentGroup=MAP_SPELL_ANCIENT},
	["Freeze"]=			{id=206,		ParentGroup=MAP_SPELL_ANCIENT},
	["Freeze II"]=		{id=207,		ParentGroup=MAP_SPELL_ANCIENT},
	["Tornado"]=		{id=208,		ParentGroup=MAP_SPELL_ANCIENT},
	["Tornado II"]=		{id=209,		ParentGroup=MAP_SPELL_ANCIENT},
	["Quake"]=			{id=210,		ParentGroup=MAP_SPELL_ANCIENT},
	["Quake II"]=		{id=211,		ParentGroup=MAP_SPELL_ANCIENT},
	["Burst"]=			{id=212,		ParentGroup=MAP_SPELL_ANCIENT},
	["Burst II"]=		{id=213,		ParentGroup=MAP_SPELL_ANCIENT},
	["Flood"]=			{id=214,		ParentGroup=MAP_SPELL_ANCIENT},
	["Flood II"]=		{id=215,		ParentGroup=MAP_SPELL_ANCIENT},
	["Gravity"]=		{id=216,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Gravity II"]=		{id=217,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Meteor"]=			{id=218,		ParentGroup=MAP_SPELL_DEFAULT},
	["Comet"]=			{id=219,		ParentGroup=MAP_SPELL_DEFAULT},
	["Poison"]=			{id=220,		ParentGroup=MAP_SPELL_POISON},
	["Poison II"]=		{id=221,		ParentGroup=MAP_SPELL_POISON},
	["Poison III"]=		{id=222,		ParentGroup=MAP_SPELL_POISON},
	["Poison IV"]=		{id=223,		ParentGroup=MAP_SPELL_POISON},
	["Poison V"]=		{id=224,		ParentGroup=MAP_SPELL_POISON},
	["Poisonga"]=		{id=225,		ParentGroup=MAP_SPELL_POISON},
	["Poisonga II"]=	{id=226,		ParentGroup=MAP_SPELL_POISON},
	["Poisonga III"]=	{id=227,		ParentGroup=MAP_SPELL_POISON},
	["Poisonga IV"]=	{id=228,		ParentGroup=MAP_SPELL_POISON},
	["Poisonga V"]=		{id=229,		ParentGroup=MAP_SPELL_POISON},
	["Bio"]=			{id=230,		ParentGroup=MAP_SPELL_BIO},
	["Bio II"]=			{id=231,		ParentGroup=MAP_SPELL_BIO},
	["Bio III"]=		{id=232,		ParentGroup=MAP_SPELL_BIO},
	["Bio IV"]=			{id=233,		ParentGroup=MAP_SPELL_BIO},
	["Bio V"]=			{id=234,		ParentGroup=MAP_SPELL_BIO},
	["Burn"]=			{id=235,		ParentGroup=MAP_SPELL_ELEMENTAL_DEBUFF},
	["Frost"]=			{id=236,		ParentGroup=MAP_SPELL_ELEMENTAL_DEBUFF},
	["Choke"]=			{id=237,		ParentGroup=MAP_SPELL_ELEMENTAL_DEBUFF},
	["Rasp"]=			{id=238,		ParentGroup=MAP_SPELL_ELEMENTAL_DEBUFF},
	["Shock"]=			{id=239,		ParentGroup=MAP_SPELL_ELEMENTAL_DEBUFF},
	["Drown"]=			{id=240,		ParentGroup=MAP_SPELL_ELEMENTAL_DEBUFF},
	["Retrace"]=		{id=241,		ParentGroup=MAP_SPELL_TELEPORT},
	["Absorb-ACC"]=		{id=242,		ParentGroup=MAP_SPELL_ABSORB},
	["Absorb-Attri"]=	{id=243,		ParentGroup=MAP_SPELL_ABSORB},
	["Meteor II"]=		{id=244,		ParentGroup=MAP_SPELL_DEFAULT},
	["Drain"]=			{id=245,		ParentGroup=MAP_SPELL_DRAIN},
	["Drain II"]=		{id=246,		ParentGroup=MAP_SPELL_DRAIN},
	["Aspir"]=			{id=247,		ParentGroup=MAP_SPELL_ASPIR},
	["Aspir II"]=		{id=248,		ParentGroup=MAP_SPELL_ASPIR},
	["Blaze Spikes"]=	{id=249,		ParentGroup=MAP_SPELL_SPIKES},
	["Ice Spikes"]=		{id=250,		ParentGroup=MAP_SPELL_SPIKES},
	["Shock Spikes"]=	{id=251,		ParentGroup=MAP_SPELL_SPIKES},
	["Stun"]=			{id=252,		ParentGroup=MAP_SPELL_DEFAULT},
	["Sleep"]=			{id=253,		ParentGroup=MAP_ENFEEBLE_DURATION},
	["Blind"]=			{id=254,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Break"]=			{id=255,		ParentGroup=MAP_ENFEEBLE_DURATION},
	["Virus"]=			{id=256,		ParentGroup=MAP_SPELL_DEFAULT},
	["Curse"]=			{id=257,		ParentGroup=MAP_SPELL_DEFAULT},
	["Bind"]=			{id=258,		ParentGroup=MAP_ENFEEBLE_DURATION},
	["Sleep II"]=		{id=259,		ParentGroup=MAP_ENFEEBLE_DURATION},
	["Dispel"]=			{id=260,		ParentGroup=MAP_SPELL_DISPEL},
	["Warp"]=			{id=261,		ParentGroup=MAP_SPELL_WARP},
	["Warp II"]=		{id=262,		ParentGroup=MAP_SPELL_WARP},
	["Escape"]=			{id=263,		ParentGroup=MAP_SPELL_DEFAULT},
	["Tractor"]=		{id=264,		ParentGroup=MAP_SPELL_DEFAULT},
	["Tractor II"]=		{id=265,		ParentGroup=MAP_SPELL_DEFAULT},
	["Absorb-STR"]=		{id=266,		ParentGroup=MAP_SPELL_ABSORB},
	["Absorb-DEX"]=		{id=267,		ParentGroup=MAP_SPELL_ABSORB},
	["Absorb-VIT"]=		{id=268,		ParentGroup=MAP_SPELL_ABSORB},
	["Absorb-AGI"]=		{id=269,		ParentGroup=MAP_SPELL_ABSORB},
	["Absorb-INT"]=		{id=270,		ParentGroup=MAP_SPELL_ABSORB},
	["Absorb-MND"]=		{id=271,		ParentGroup=MAP_SPELL_ABSORB},
	["Absorb-CHR"]=		{id=272,		ParentGroup=MAP_SPELL_ABSORB},
	["Sleepga"]=		{id=273,		ParentGroup=MAP_ENFEEBLE_DURATION},
	["Sleepga II"]=		{id=274,		ParentGroup=MAP_ENFEEBLE_DURATION},
	["Absorb-TP"]=		{id=275,		ParentGroup=MAP_SPELL_ABSORB},
	["Blind II"]=		{id=276,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Dread Spikes"]=	{id=277,		ParentGroup=MAP_SPELL_DEFAULT},
	["Geohelix"]=		{id=278,		ParentGroup=MAP_SPELL_HELIX},
	["Hydrohelix"]=		{id=279,		ParentGroup=MAP_SPELL_HELIX},
	["Anemohelix"]=		{id=280,		ParentGroup=MAP_SPELL_HELIX},
	["Pyrohelix"]=		{id=281,		ParentGroup=MAP_SPELL_HELIX},
	["Cryohelix"]=		{id=282,		ParentGroup=MAP_SPELL_HELIX},
	["Ionohelix"]=		{id=283,		ParentGroup=MAP_SPELL_HELIX},
	["Noctohelix"]=		{id=284,		ParentGroup=MAP_SPELL_HELIX},
	["Luminohelix"]=	{id=285,		ParentGroup=MAP_SPELL_HELIX},
	["Addle"]=			{id=286,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Klimaform"]=		{id=287,		ParentGroup=MAP_SPELL_DEFAULT},
	["Fire Spirit"]=	{id=288,		ParentGroup=MAP_SPELL_SPIRIT},
	["Ice Spirit"]=		{id=289,		ParentGroup=MAP_SPELL_SPIRIT},
	["Air Spirit"]=		{id=290,		ParentGroup=MAP_SPELL_SPIRIT},
	["Earth Spirit"]=	{id=291,		ParentGroup=MAP_SPELL_SPIRIT},
	["Thunder Spirit"]=	{id=292,		ParentGroup=MAP_SPELL_SPIRIT},
	["Water Spirit"]=	{id=293,		ParentGroup=MAP_SPELL_SPIRIT},
	["Light Spirit"]=	{id=294,		ParentGroup=MAP_SPELL_SPIRIT},
	["Dark Spirit"]=	{id=295,		ParentGroup=MAP_SPELL_SPIRIT},
	["Carbuncle"]=		{id=296,		ParentGroup=MAP_SPELL_AVATAR},
	["Fenrir"]=			{id=297,		ParentGroup=MAP_SPELL_AVATAR},
	["Ifrit"]=			{id=298,		ParentGroup=MAP_SPELL_AVATAR},
	["Titan"]=			{id=299,		ParentGroup=MAP_SPELL_AVATAR},
	["Leviathan"]=		{id=300,		ParentGroup=MAP_SPELL_AVATAR},
	["Garuda"]=			{id=301,		ParentGroup=MAP_SPELL_AVATAR},
	["Shiva"]=			{id=302,		ParentGroup=MAP_SPELL_AVATAR},
	["Ramuh"]=			{id=303,		ParentGroup=MAP_SPELL_AVATAR},
	["Diabolos"]=		{id=304,		ParentGroup=MAP_SPELL_AVATAR},
	["Odin"]=			{id=305,		ParentGroup=MAP_SPELL_AVATAR},
	["Alexander"]=		{id=306,		ParentGroup=MAP_SPELL_AVATAR},
	["Cait Sith"]=		{id=307,		ParentGroup=MAP_SPELL_AVATAR},
	["Animus Augeo"]=	{id=308,		ParentGroup=MAP_SPELL_DEFAULT},
	["Animus Minuo"]=	{id=309,		ParentGroup=MAP_SPELL_DEFAULT},
	["Enlight"]=		{id=310,		ParentGroup=MAP_SPELL_ENLIGHT},
	["Endark"]=			{id=311,		ParentGroup=MAP_SPELL_ENDARK},
	["Enfire II"]=		{id=312,		ParentGroup=MAP_SPELL_ENSPELL2},
	["Enblizzard II"]=	{id=313,		ParentGroup=MAP_SPELL_ENSPELL2},
	["Enaero II"]=		{id=314,		ParentGroup=MAP_SPELL_ENSPELL2},
	["Enstone II"]=		{id=315,		ParentGroup=MAP_SPELL_ENSPELL2},
	["Enthunder II"]=	{id=316,		ParentGroup=MAP_SPELL_ENSPELL2},
	["Enwater II"]=		{id=317,		ParentGroup=MAP_SPELL_ENSPELL2},
	["Monomi: Ichi"]=	{id=318,		ParentGroup=MAP_SPELL_DEFAULT},
	["Aisha: Ichi"]=	{id=319,		ParentGroup=MAP_SPELL_NINJUTSU_DEBUFF},
	["Katon: Ichi"]=	{id=320,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Katon: Ni"]=		{id=321,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Katon: San"]=		{id=322,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Hyoton: Ichi"]=	{id=323,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Hyoton: Ni"]=		{id=324,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Hyoton: San"]=	{id=325,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Huton: Ichi"]=	{id=326,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Huton: Ni"]=		{id=327,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Huton: San"]=		{id=328,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Doton: Ichi"]=	{id=329,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Doton: Ni"]=		{id=330,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Doton: San"]=		{id=331,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Raiton: Ichi"]=	{id=332,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Raiton: Ni"]=		{id=333,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Raiton: San"]=	{id=334,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Suiton: Ichi"]=	{id=335,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Suiton: Ni"]=		{id=336,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Suiton: San"]=	{id=337,		ParentGroup=MAP_SPELL_NINJUTSU_ELEMENT},
	["Utsusemi: Ichi"]=	{id=338,		ParentGroup=MAP_SPELL_UTSUSEMI},
	["Utsusemi: Ni"]=	{id=339,		ParentGroup=MAP_SPELL_UTSUSEMI},
	["Utsusemi: San"]=	{id=340,		ParentGroup=MAP_SPELL_UTSUSEMI},
	["Jubaku: Ichi"]=	{id=341,		ParentGroup=MAP_SPELL_NINJUTSU_DEBUFF},
	["Jubaku: Ni"]=		{id=342,		ParentGroup=MAP_SPELL_NINJUTSU_DEBUFF},
	["Jubaku: San"]=	{id=343,		ParentGroup=MAP_SPELL_NINJUTSU_DEBUFF},
	["Hojo: Ichi"]=		{id=344,		ParentGroup=MAP_SPELL_NINJUTSU_DEBUFF},
	["Hojo: Ni"]=		{id=345,		ParentGroup=MAP_SPELL_NINJUTSU_DEBUFF},
	["Hojo: San"]=		{id=346,		ParentGroup=MAP_SPELL_NINJUTSU_DEBUFF},
	["Kurayami: Ichi"]=	{id=347,		ParentGroup=MAP_SPELL_NINJUTSU_DEBUFF},
	["Kurayami: Ni"]=	{id=348,		ParentGroup=MAP_SPELL_NINJUTSU_DEBUFF},
	["Kurayami: San"]=	{id=349,		ParentGroup=MAP_SPELL_NINJUTSU_DEBUFF},
	["Dokumori: Ichi"]=	{id=350,		ParentGroup=MAP_SPELL_NINJUTSU_DEBUFF},
	["Dokumori: Ni"]=	{id=351,		ParentGroup=MAP_SPELL_NINJUTSU_DEBUFF},
	["Dokumori: San"]=	{id=352,		ParentGroup=MAP_SPELL_NINJUTSU_DEBUFF},
	["Tonko: Ichi"]=	{id=353,		ParentGroup=MAP_SPELL_DEFAULT},
	["Tonko: Ni"]=		{id=354,		ParentGroup=MAP_SPELL_DEFAULT},
	["Siren"]=			{id=355,		ParentGroup=MAP_SPELL_AVATAR},
	["Paralyga"]=		{id=356,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Slowga"]=			{id=357,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Hastega"]=		{id=358,		ParentGroup=MAP_SPELL_HASTE},
	["Silencega"]=		{id=359,		ParentGroup=MAP_ENFEEBLE_DURATION},
	["Dispelga"]=		{id=360,		ParentGroup=MAP_SPELL_DISPEL},
	["Blindga"]=		{id=361,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Bindga"]=			{id=362,		ParentGroup=MAP_ENFEEBLE_DURATION},
	["Sleepga"]=		{id=363,		ParentGroup=MAP_ENFEEBLE_DURATION},
	["Sleepga II"]=		{id=364,		ParentGroup=MAP_ENFEEBLE_DURATION},
	["Breakga"]=		{id=365,		ParentGroup=MAP_ENFEEBLE_DURATION},
	["Graviga"]=		{id=366,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Death"]=			{id=367,		ParentGroup=MAP_SPELL_DEFAULT},
	["Foe Requiem"]=		{id=368,		ParentGroup=MAP_SPELL_REQUIEM},
	["Foe Requiem II"]=		{id=369,		ParentGroup=MAP_SPELL_REQUIEM},
	["Foe Requiem III"]=	{id=370,		ParentGroup=MAP_SPELL_REQUIEM},
	["Foe Requiem IV"]=		{id=371,		ParentGroup=MAP_SPELL_REQUIEM},
	["Foe Requiem V"]=		{id=372,		ParentGroup=MAP_SPELL_REQUIEM},
	["Foe Requiem VI"]=		{id=373,		ParentGroup=MAP_SPELL_REQUIEM},
	["Foe Requiem VII"]=	{id=374,		ParentGroup=MAP_SPELL_REQUIEM},
	["Foe Requiem VIII"]=	{id=375,		ParentGroup=MAP_SPELL_REQUIEM},
	["Horde Lullaby"]=		{id=376,		ParentGroup=MAP_SPELL_LULLABY},
	["Horde Lullaby II"]=	{id=377,		ParentGroup=MAP_SPELL_LULLABY},
	["Army's Paeon"]=		{id=378,		ParentGroup=MAP_SPELL_PAEON},
	["Army's Paeon II"]=	{id=379,		ParentGroup=MAP_SPELL_PAEON},
	["Army's Paeon III"]=	{id=380,		ParentGroup=MAP_SPELL_PAEON},
	["Army's Paeon IV"]=	{id=381,		ParentGroup=MAP_SPELL_PAEON},
	["Army's Paeon V"]=		{id=382,		ParentGroup=MAP_SPELL_PAEON},
	["Army's Paeon VI"]=	{id=383,		ParentGroup=MAP_SPELL_PAEON},
	["Army's Paeon VII"]=	{id=384,		ParentGroup=MAP_SPELL_PAEON},
	["Army's Paeon VIII"]=	{id=385,		ParentGroup=MAP_SPELL_PAEON},
	["Mage's Ballad"]=		{id=386,		ParentGroup=MAP_SPELL_BALLAD},
	["Mage's Ballad II"]=	{id=387,		ParentGroup=MAP_SPELL_BALLAD},
	["Mage's Ballad III"]=	{id=388,		ParentGroup=MAP_SPELL_BALLAD},
	["Knight's Minne"]=		{id=389,		ParentGroup=MAP_SPELL_MINNE},
	["Knight's Minne II"]=	{id=390,		ParentGroup=MAP_SPELL_MINNE},
	["Knight's Minne III"]=	{id=391,		ParentGroup=MAP_SPELL_MINNE},
	["Knight's Minne IV"]=	{id=392,		ParentGroup=MAP_SPELL_MINNE},
	["Knight's Minne V"]=	{id=393,		ParentGroup=MAP_SPELL_MINNE},
	["Valor Minuet"]=		{id=394,		ParentGroup=MAP_SPELL_MINUET},
	["Valor Minuet II"]=	{id=395,		ParentGroup=MAP_SPELL_MINUET},
	["Valor Minuet III"]=	{id=396,		ParentGroup=MAP_SPELL_MINUET},
	["Valor Minuet IV"]=	{id=397,		ParentGroup=MAP_SPELL_MINUET},
	["Valor Minuet V"]=		{id=398,		ParentGroup=MAP_SPELL_MINUET},
	["Sword Madrigal"]=		{id=399,		ParentGroup=MAP_SPELL_MADRIGAL},
	["Blade Madrigal"]=		{id=400,		ParentGroup=MAP_SPELL_MADRIGAL},
	["Hunter's Prelude"]=	{id=401,		ParentGroup=MAP_SPELL_PRELUDE},
	["Archer's Prelude"]=	{id=402,		ParentGroup=MAP_SPELL_PRELUDE},
	["Sheepfoe Mambo"]=		{id=403,		ParentGroup=MAP_SPELL_MAMBO},
	["Dragonfoe Mambo"]=	{id=404,		ParentGroup=MAP_SPELL_MAMBO},
	["Fowl Aubade"]=		{id=405,		ParentGroup=MAP_SPELL_DEFAULT},
	["Herb Pastoral"]=		{id=406,		ParentGroup=MAP_SPELL_DEFAULT},
	["Chocobo Hum"]=		{id=407,		ParentGroup=MAP_SPELL_DEFAULT},
	["Shining Fantasia"]=	{id=408,		ParentGroup=MAP_SPELL_DEFAULT},
	["Scop's Operetta"]=	{id=409,		ParentGroup=MAP_SPELL_DEFAULT},
	["Puppet's Operetta"]=	{id=410,		ParentGroup=MAP_SPELL_DEFAULT},
	["Jester's Operetta"]=	{id=411,		ParentGroup=MAP_SPELL_DEFAULT},
	["Gold Capriccio"]=		{id=412,		ParentGroup=MAP_SPELL_DEFAULT},
	["Devotee Serenade"]=	{id=413,		ParentGroup=MAP_SPELL_DEFAULT},
	["Warding Round"]=		{id=414,		ParentGroup=MAP_SPELL_DEFAULT},
	["Goblin Gavotte"]=		{id=415,		ParentGroup=MAP_SPELL_DEFAULT},
	["Cactuar Fugue"]=		{id=416,		ParentGroup=MAP_SPELL_DEFAULT},
	["Honor March"]=		{id=417,		ParentGroup=MAP_SPELL_MARCH},
	["Aria of Passion"]=	{id=418,		ParentGroup=MAP_SPELL_DEFAULT},
	["Advancing March"]=	{id=419,		ParentGroup=MAP_SPELL_MARCH},
	["Victory March"]=		{id=420,		ParentGroup=MAP_SPELL_MARCH},
	["Battlefield Elegy"]=	{id=421,		ParentGroup=MAP_SPELL_ELEGY},
	["Carnage Elegy"]=		{id=422,		ParentGroup=MAP_SPELL_ELEGY},
	["Massacre Elegy"]=		{id=423,		ParentGroup=MAP_SPELL_ELEGY},
	["Sinewy Etude"]=		{id=424,		ParentGroup=MAP_SPELL_ETUDE},
	["Dextrous Etude"]=		{id=425,		ParentGroup=MAP_SPELL_ETUDE},
	["Vivacious Etude"]=	{id=426,		ParentGroup=MAP_SPELL_ETUDE},
	["Quick Etude"]=		{id=427,		ParentGroup=MAP_SPELL_ETUDE},
	["Learned Etude"]=		{id=428,		ParentGroup=MAP_SPELL_ETUDE},
	["Spirited Etude"]=		{id=429,		ParentGroup=MAP_SPELL_ETUDE},
	["Enchanting Etude"]=	{id=430,		ParentGroup=MAP_SPELL_ETUDE},
	["Herculean Etude"]=	{id=431,		ParentGroup=MAP_SPELL_ETUDE},
	["Uncanny Etude"]=		{id=432,		ParentGroup=MAP_SPELL_ETUDE},
	["Vital Etude"]=		{id=433,		ParentGroup=MAP_SPELL_ETUDE},
	["Swift Etude"]=		{id=434,		ParentGroup=MAP_SPELL_ETUDE},
	["Sage Etude"]=			{id=435,		ParentGroup=MAP_SPELL_ETUDE},
	["Logical Etude"]=		{id=436,		ParentGroup=MAP_SPELL_ETUDE},
	["Bewitching Etude"]=	{id=437,		ParentGroup=MAP_SPELL_ETUDE},
	["Fire Carol"]=			{id=438,		ParentGroup=MAP_SPELL_CAROL},
	["Ice Carol"]=			{id=439,		ParentGroup=MAP_SPELL_CAROL},
	["Wind Carol"]=			{id=440,		ParentGroup=MAP_SPELL_CAROL},
	["Earth Carol"]=		{id=441,		ParentGroup=MAP_SPELL_CAROL},
	["Lightning Carol"]=	{id=442,		ParentGroup=MAP_SPELL_CAROL},
	["Water Carol"]=		{id=443,		ParentGroup=MAP_SPELL_CAROL},
	["Light Carol"]=		{id=444,		ParentGroup=MAP_SPELL_CAROL},
	["Dark Carol"]=			{id=445,		ParentGroup=MAP_SPELL_CAROL},
	["Fire Carol II"]=		{id=446,		ParentGroup=MAP_SPELL_CAROL},
	["Ice Carol II"]=		{id=447,		ParentGroup=MAP_SPELL_CAROL},
	["Wind Carol II"]=		{id=448,		ParentGroup=MAP_SPELL_CAROL},
	["Earth Carol II"]=		{id=449,		ParentGroup=MAP_SPELL_CAROL},
	["Lightning Carol II"]=	{id=450,		ParentGroup=MAP_SPELL_CAROL},
	["Water Carol II"]=		{id=451,		ParentGroup=MAP_SPELL_CAROL},
	["Light Carol II"]=		{id=452,		ParentGroup=MAP_SPELL_CAROL},
	["Dark Carol II"]=		{id=453,		ParentGroup=MAP_SPELL_CAROL},
	["Fire Threnody"]=		{id=454,		ParentGroup=MAP_SPELL_THRENODY},
	["Ice Threnody"]=		{id=455,		ParentGroup=MAP_SPELL_THRENODY},
	["Wind Threnody"]=		{id=456,		ParentGroup=MAP_SPELL_THRENODY},
	["Earth Threnody"]=		{id=457,		ParentGroup=MAP_SPELL_THRENODY},
	["Ltng. Threnody"]=		{id=458,		ParentGroup=MAP_SPELL_THRENODY},
	["Water Threnody"]=		{id=459,		ParentGroup=MAP_SPELL_THRENODY},
	["Light Threnody"]=		{id=460,		ParentGroup=MAP_SPELL_THRENODY},
	["Dark Threnody"]=		{id=461,		ParentGroup=MAP_SPELL_THRENODY},
	["Magic Finale"]=		{id=462,		ParentGroup=MAP_SPELL_DEFAULT},
	["Foe Lullaby"]=		{id=463,		ParentGroup=MAP_SPELL_LULLABY},
	["Goddess's Hymnus"]=	{id=464,		ParentGroup=MAP_SPELL_DEFAULT},
	["Chocobo Mazurka"]=	{id=465,		ParentGroup=MAP_SPELL_MAZURKA},
	["Maiden's Virelai"]=	{id=466,		ParentGroup=MAP_SPELL_DEFAULT},
	["Raptor Mazurka"]=		{id=467,		ParentGroup=MAP_SPELL_MAZURKA},
	["Foe Sirvente"]=		{id=468,		ParentGroup=MAP_SPELL_DEFAULT},
	["Adventurer's Dirge"]=	{id=469,		ParentGroup=MAP_SPELL_DEFAULT},
	["Sentinel's Scherzo"]=	{id=470,		ParentGroup=MAP_SPELL_DEFAULT},
	["Foe Lullaby II"]=		{id=471,		ParentGroup=MAP_SPELL_LULLABY},
	["Pining Nocturne"]=	{id=472,		ParentGroup=MAP_SPELL_DEFAULT},
	["Refresh II"]=			{id=473,		ParentGroup=MAP_SPELL_REFRESH},
	["Cura II"]=			{id=474,		ParentGroup=MAP_SPELL_CURAGA},
	["Cura III"]=			{id=475,		ParentGroup=MAP_SPELL_CURAGA},
	["Crusade"]=			{id=476,		ParentGroup=MAP_SPELL_DEFAULT},
	["Regen IV"]=			{id=477,		ParentGroup=MAP_SPELL_REGEN},
	["Embrava"]=			{id=478,		ParentGroup=MAP_SPELL_DEFAULT},
	["Boost-STR"]=			{id=479,		ParentGroup=MAP_SPELL_BOOST},
	["Boost-DEX"]=			{id=480,		ParentGroup=MAP_SPELL_BOOST},
	["Boost-VIT"]=			{id=481,		ParentGroup=MAP_SPELL_BOOST},
	["Boost-AGI"]=			{id=482,		ParentGroup=MAP_SPELL_BOOST},
	["Boost-INT"]=			{id=483,		ParentGroup=MAP_SPELL_BOOST},
	["Boost-MND"]=			{id=484,		ParentGroup=MAP_SPELL_BOOST},
	["Boost-CHR"]=			{id=485,		ParentGroup=MAP_SPELL_BOOST},
	["Gain-STR"]=			{id=486,		ParentGroup=MAP_SPELL_GAIN},
	["Gain-DEX"]=			{id=487,		ParentGroup=MAP_SPELL_GAIN},
	["Gain-VIT"]=			{id=488,		ParentGroup=MAP_SPELL_GAIN},
	["Gain-AGI"]=			{id=489,		ParentGroup=MAP_SPELL_GAIN},
	["Gain-INT"]=			{id=490,		ParentGroup=MAP_SPELL_GAIN},
	["Gain-MND"]=			{id=491,		ParentGroup=MAP_SPELL_GAIN},
	["Gain-CHR"]=			{id=492,		ParentGroup=MAP_SPELL_GAIN},
	["Temper"]=				{id=493,		ParentGroup=MAP_SPELL_TEMPER},
	["Arise"]=				{id=494,		ParentGroup=MAP_SPELL_DEFAULT},
	["Adloquium"]=			{id=495,		ParentGroup=MAP_SPELL_DEFAULT},
	["Firaja"]=				{id=496,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blizzaja"]=			{id=497,		ParentGroup=MAP_SPELL_DEFAULT},
	["Aeroja"]=				{id=498,		ParentGroup=MAP_SPELL_DEFAULT},
	["Stoneja"]=			{id=499,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thundaja"]=			{id=500,		ParentGroup=MAP_SPELL_DEFAULT},
	["Waterja"]=			{id=501,		ParentGroup=MAP_SPELL_DEFAULT},
	["Kaustra"]=			{id=502,		ParentGroup=MAP_SPELL_DEFAULT},
	["Impact"]=				{id=503,		ParentGroup=MAP_SPELL_DEFAULT},
	["Regen V"]=			{id=504,		ParentGroup=MAP_SPELL_REGEN},
	["Gekka: Ichi"]=		{id=505,		ParentGroup=MAP_SPELL_DEFAULT},
	["Yain: Ichi"]=			{id=506,		ParentGroup=MAP_SPELL_DEFAULT},
	["Myoshu: Ichi"]=		{id=507,		ParentGroup=MAP_SPELL_DEFAULT},
	["Yurin: Ichi"]=		{id=508,		ParentGroup=MAP_SPELL_DEFAULT},
	["Kakka: Ichi"]=		{id=509,		ParentGroup=MAP_SPELL_DEFAULT},
	["Migawari: Ichi"]=		{id=510,		ParentGroup=MAP_SPELL_DEFAULT},
	["Haste II"]=			{id=511,		ParentGroup=MAP_SPELL_HASTE},
	["Venom Shell"]=		{id=513,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Maelstrom"]=			{id=515,		ParentGroup=MAP_SPELL_DEFAULT},
	["Metallic Body"]=		{id=517,		ParentGroup=MAP_SKILL_ENHANCING},
	["Screwdriver"]=		{id=519,		ParentGroup=MAP_SPELL_DEFAULT},
	["MP Drainkiss"]=		{id=521,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Death Ray"]=			{id=522,		ParentGroup=MAP_SPELL_DEFAULT},
	["Sandspin"]=			{id=524,		ParentGroup=MAP_SPELL_DEFAULT},
	["Smite of Rage"]=		{id=527,		ParentGroup=MAP_SPELL_DEFAULT},
	["Bludgeon"]=			{id=529,		ParentGroup=MAP_SPELL_DEFAULT},
	["Refueling"]=			{id=530,		ParentGroup=MAP_SPELL_DEFAULT},
	["Ice Break"]=			{id=531,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blitzstrahl"]=		{id=532,		ParentGroup=MAP_SPELL_DEFAULT},
	["Self-Destruct"]=		{id=533,		ParentGroup=MAP_SPELL_DEFAULT},
	["Mysterious Light"]=	{id=534,		ParentGroup=MAP_SPELL_DEFAULT},
	["Cold Wave"]=			{id=535,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Poison Breath"]=		{id=536,		ParentGroup=MAP_SPELL_DEFAULT},
	["Stinking Gas"]=		{id=537,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Memento Mori"]=		{id=538,		ParentGroup=MAP_SPELL_DEFAULT},
	["Terror Touch"]=		{id=539,		ParentGroup=MAP_SPELL_DEFAULT},
	["Spinal Cleave"]=		{id=540,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blood Saber"]=		{id=541,		ParentGroup=MAP_SPELL_DEFAULT},
	["Digest"]=				{id=542,		ParentGroup=MAP_SPELL_DEFAULT},
	["Mandibular Bite"]=	{id=543,		ParentGroup=MAP_SPELL_DEFAULT},
	["Cursed Sphere"]=		{id=544,		ParentGroup=MAP_SPELL_DEFAULT},
	["Sickle Slash"]=		{id=545,		ParentGroup=MAP_SPELL_DEFAULT},
	["Cocoon"]=				{id=547,		ParentGroup=MAP_SPELL_DEFAULT},
	["Filamented Hold"]=	{id=548,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Pollen"]=				{id=549,		ParentGroup=MAP_SPELL_CURE},
	["Power Attack"]=		{id=551,		ParentGroup=MAP_SPELL_DEFAULT},
	["Death Scissors"]=		{id=554,		ParentGroup=MAP_SPELL_DEFAULT},
	["Magnetite Cloud"]=	{id=555,		ParentGroup=MAP_SPELL_DEFAULT},
	["Eyes On Me"]=			{id=557,		ParentGroup=MAP_SPELL_DEFAULT},
	["Frenetic Rip"]=		{id=560,		ParentGroup=MAP_SPELL_DEFAULT},
	["Frightful Roar"]=		{id=561,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Hecatomb Wave"]=		{id=563,		ParentGroup=MAP_SPELL_DEFAULT},
	["Body Slam"]=			{id=564,		ParentGroup=MAP_SPELL_DEFAULT},
	["Radiant Breath"]=		{id=565,		ParentGroup=MAP_SPELL_DEFAULT},
	["Helldive"]=			{id=567,		ParentGroup=MAP_SPELL_DEFAULT},
	["Jet Stream"]=			{id=569,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blood Drain"]=		{id=570,		ParentGroup=MAP_SPELL_DEFAULT},
	["Sound Blast"]=		{id=572,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Feather Tickle"]=		{id=573,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Feather Barrier"]=	{id=574,		ParentGroup=MAP_SPELL_DEFAULT},
	["Jettatura"]=			{id=575,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Yawn"]=				{id=576,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Foot Kick"]=			{id=577,		ParentGroup=MAP_SPELL_DEFAULT},
	["Wild Carrot"]=		{id=578,		ParentGroup=MAP_SPELL_CURE},
	["Voracious Trunk"]=	{id=579,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Healing Breeze"]=		{id=581,		ParentGroup=MAP_SPELL_CURE},
	["Chaotic Eye"]=		{id=582,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Sheep Song"]=			{id=584,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Ram Charge"]=			{id=585,		ParentGroup=MAP_SPELL_DEFAULT},
	["Claw Cyclone"]=		{id=587,		ParentGroup=MAP_SPELL_DEFAULT},
	["Lowing"]=				{id=588,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Dimensional Death"]=	{id=589,		ParentGroup=MAP_SPELL_DEFAULT},
	["Heat Breath"]=		{id=591,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blank Gaze"]=			{id=592,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Magic Fruit"]=		{id=593,		ParentGroup=MAP_SPELL_CURE},
	["Uppercut"]=			{id=594,		ParentGroup=MAP_SPELL_DEFAULT},
	["1000 Needles"]=		{id=595,		ParentGroup=MAP_SPELL_DEFAULT},
	["Pinecone Bomb"]=		{id=596,		ParentGroup=MAP_SPELL_DEFAULT},
	["Sprout Smack"]=		{id=597,		ParentGroup=MAP_SPELL_DEFAULT},
	["Soporific"]=			{id=598,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Queasyshroom"]=		{id=599,		ParentGroup=MAP_SPELL_DEFAULT},
	["Wild Oats"]=			{id=603,		ParentGroup=MAP_SPELL_DEFAULT},
	["Bad Breath"]=			{id=604,		ParentGroup=MAP_SPELL_DEFAULT},
	["Geist Wall"]=			{id=605,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Awful Eye"]=			{id=606,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Frost Breath"]=		{id=608,		ParentGroup=MAP_SPELL_DEFAULT},
	["Infrasonics"]=		{id=610,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Disseverment"]=		{id=611,		ParentGroup=MAP_SPELL_DEFAULT},
	["Actinic Burst"]=		{id=612,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Reactor Cool"]=		{id=613,		ParentGroup=MAP_SPELL_DEFAULT},
	["Saline Coat"]=		{id=614,		ParentGroup=MAP_SPELL_DEFAULT},
	["Plasma Charge"]=		{id=615,		ParentGroup=MAP_SPELL_DEFAULT},
	["Temporal Shift"]=		{id=616,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Vertical Cleave"]=	{id=617,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blastbomb"]=			{id=618,		ParentGroup=MAP_SPELL_DEFAULT},
	["Battle Dance"]=		{id=620,		ParentGroup=MAP_SPELL_DEFAULT},
	["Sandspray"]=			{id=621,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Grand Slam"]=			{id=622,		ParentGroup=MAP_SPELL_DEFAULT},
	["Head Butt"]=			{id=623,		ParentGroup=MAP_SPELL_DEFAULT},
	["Bomb Toss"]=			{id=626,		ParentGroup=MAP_SPELL_DEFAULT},
	["Frypan"]=				{id=628,		ParentGroup=MAP_SPELL_DEFAULT},
	["Flying Hip Press"]=	{id=629,		ParentGroup=MAP_SPELL_DEFAULT},
	["Hydro Shot"]=			{id=631,		ParentGroup=MAP_SPELL_DEFAULT},
	["Diamondhide"]=		{id=632,		ParentGroup=MAP_SKILL_ENHANCING},
	["Enervation"]=			{id=633,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Light of Penance"]=	{id=634,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Warm-Up"]=			{id=636,		ParentGroup=MAP_SPELL_DEFAULT},
	["Firespit"]=			{id=637,		ParentGroup=MAP_SPELL_DEFAULT},
	["Feather Storm"]=		{id=638,		ParentGroup=MAP_SPELL_DEFAULT},
	["Tail Slap"]=			{id=640,		ParentGroup=MAP_SPELL_DEFAULT},
	["Hysteric Barrage"]=	{id=641,		ParentGroup=MAP_SPELL_DEFAULT},
	["Amplification"]=		{id=642,		ParentGroup=MAP_SPELL_DEFAULT},
	["Cannonball"]=			{id=643,		ParentGroup=MAP_SPELL_DEFAULT},
	["Mind Blast"]=			{id=644,		ParentGroup=MAP_SPELL_DEFAULT},
	["Exuviation"]=			{id=645,		ParentGroup=MAP_SPELL_CURE},
	["Magic Hammer"]=		{id=646,		ParentGroup=MAP_SPELL_DEFAULT},
	["Zephyr Mantle"]=		{id=647,		ParentGroup=MAP_SPELL_DEFAULT},
	["Regurgitation"]=		{id=648,		ParentGroup=MAP_SPELL_DEFAULT},
	["Seedspray"]=			{id=650,		ParentGroup=MAP_SPELL_DEFAULT},
	["Corrosive Ooze"]=		{id=651,		ParentGroup=MAP_SPELL_DEFAULT},
	["Spiral Spin"]=		{id=652,		ParentGroup=MAP_SPELL_DEFAULT},
	["Asuran Claws"]=		{id=653,		ParentGroup=MAP_SPELL_DEFAULT},
	["Sub-zero Smash"]=		{id=654,		ParentGroup=MAP_SPELL_DEFAULT},
	["Triumphant Roar"]=	{id=655,		ParentGroup=MAP_SPELL_DEFAULT},
	["Acrid Stream"]=		{id=656,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blazing Bound"]=		{id=657,		ParentGroup=MAP_SPELL_DEFAULT},
	["Plenilune Embrace"]=	{id=658,		ParentGroup=MAP_SPELL_CURE},
	["Demoralizing Roar"]=	{id=659,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Cimicine Discharge"]=	{id=660,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Animating Wail"]=		{id=661,		ParentGroup=MAP_SPELL_DEFAULT},
	["Battery Charge"]=		{id=662,		ParentGroup=MAP_SPELL_REFRESH},
	["Leafstorm"]=			{id=663,		ParentGroup=MAP_SPELL_DEFAULT},
	["Regeneration"]=		{id=664,		ParentGroup=MAP_SPELL_REGEN},
	["Final Sting"]=		{id=665,		ParentGroup=MAP_SPELL_DEFAULT},
	["Goblin Rush"]=		{id=666,		ParentGroup=MAP_SPELL_DEFAULT},
	["Vanity Dive"]=		{id=667,		ParentGroup=MAP_SPELL_DEFAULT},
	["Magic Barrier"]=		{id=668,		ParentGroup=MAP_SKILL_ENHANCING},
	["Whirl of Rage"]=		{id=669,		ParentGroup=MAP_SPELL_DEFAULT},
	["Benthic Typhoon"]=	{id=670,		ParentGroup=MAP_SPELL_DEFAULT},
	["Auroral Drape"]=		{id=671,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Osmosis"]=			{id=672,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Quad. Continuum"]=	{id=673,		ParentGroup=MAP_SPELL_DEFAULT},
	["Fantod"]=				{id=674,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thermal Pulse"]=		{id=675,		ParentGroup=MAP_SPELL_DEFAULT},
	["Empty Thrash"]=		{id=677,		ParentGroup=MAP_SPELL_DEFAULT},
	["Dream Flower"]=		{id=678,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Occultation"]=		{id=679,		ParentGroup=MAP_SKILL_ENHANCING},
	["Charged Whisker"]=	{id=680,		ParentGroup=MAP_SPELL_DEFAULT},
	["Winds of Promy."]=	{id=681,		ParentGroup=MAP_SPELL_DEFAULT},
	["Delta Thrust"]=		{id=682,		ParentGroup=MAP_SPELL_DEFAULT},
	["Evryone. Grudge"]=	{id=683,		ParentGroup=MAP_SPELL_DEFAULT},
	["Reaving Wind"]=		{id=684,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Barrier Tusk"]=		{id=685,		ParentGroup=MAP_SPELL_DEFAULT},
	["Mortal Ray"]=			{id=686,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Water Bomb"]=			{id=687,		ParentGroup=MAP_SPELL_DEFAULT},
	["Heavy Strike"]=		{id=688,		ParentGroup=MAP_SPELL_DEFAULT},
	["Dark Orb"]=			{id=689,		ParentGroup=MAP_SPELL_DEFAULT},
	["White Wind"]=			{id=690,		ParentGroup=MAP_SPELL_CURE},
	["Sudden Lunge"]=		{id=692,		ParentGroup=MAP_SPELL_DEFAULT},
	["Quadrastrike"]=		{id=693,		ParentGroup=MAP_SPELL_DEFAULT},
	["Vapor Spray"]=		{id=694,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thunder Breath"]=		{id=695,		ParentGroup=MAP_SPELL_DEFAULT},
	["O. Counterstance"]=	{id=696,		ParentGroup=MAP_SPELL_DEFAULT},
	["Amorphic Spikes"]=	{id=697,		ParentGroup=MAP_SPELL_DEFAULT},
	["Wind Breath"]=		{id=698,		ParentGroup=MAP_SPELL_DEFAULT},
	["Barbed Crescent"]=	{id=699,		ParentGroup=MAP_SPELL_DEFAULT},
	["Nat. Meditation"]=	{id=700,		ParentGroup=MAP_SPELL_DEFAULT},
	["Tem. Upheaval"]=		{id=701,		ParentGroup=MAP_SPELL_DEFAULT},
	["Rending Deluge"]=		{id=702,		ParentGroup=MAP_SPELL_DEFAULT},
	["Embalming Earth"]=	{id=703,		ParentGroup=MAP_SPELL_DEFAULT},
	["Paralyzing Triad"]=	{id=704,		ParentGroup=MAP_SPELL_DEFAULT},
	["Foul Waters"]=		{id=705,		ParentGroup=MAP_SPELL_DEFAULT},
	["Glutinous Dart"]=		{id=706,		ParentGroup=MAP_SPELL_DEFAULT},
	["Retinal Glare"]=		{id=707,		ParentGroup=MAP_SPELL_DEFAULT},
	["Subduction"]=			{id=708,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thrashing Assault"]=	{id=709,		ParentGroup=MAP_SPELL_DEFAULT},
	["Erratic Flutter"]=	{id=710,		ParentGroup=MAP_SPELL_DEFAULT},
	["Restoral"]=			{id=711,		ParentGroup=MAP_SPELL_CURE},
	["Rail Cannon"]=		{id=712,		ParentGroup=MAP_SPELL_DEFAULT},
	["Diffusion Ray"]=		{id=713,		ParentGroup=MAP_SPELL_DEFAULT},
	["Sinker Drill"]=		{id=714,		ParentGroup=MAP_SPELL_DEFAULT},
	["Molting Plumage"]=	{id=715,		ParentGroup=MAP_SPELL_DEFAULT},
	["Nectarous Deluge"]=	{id=716,		ParentGroup=MAP_SPELL_DEFAULT},
	["Sweeping Gouge"]=		{id=717,		ParentGroup=MAP_SPELL_DEFAULT},
	["Atra. Libations"]=	{id=718,		ParentGroup=MAP_SPELL_DEFAULT},
	["Searing Tempest"]=	{id=719,		ParentGroup=MAP_SPELL_DEFAULT},
	["Spectral Floe"]=		{id=720,		ParentGroup=MAP_SPELL_DEFAULT},
	["Anvil Lightning"]=	{id=721,		ParentGroup=MAP_SPELL_DEFAULT},
	["Entomb"]=				{id=722,		ParentGroup=MAP_SPELL_DEFAULT},
	["Saurian Slide"]=		{id=723,		ParentGroup=MAP_SPELL_DEFAULT},
	["Palling Salvo"]=		{id=724,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blinding Fulgor"]=	{id=725,		ParentGroup=MAP_SPELL_DEFAULT},
	["Scouring Spate"]=		{id=726,		ParentGroup=MAP_SPELL_DEFAULT},
	["Silent Storm"]=		{id=727,		ParentGroup=MAP_SPELL_DEFAULT},
	["Tenebral Crush"]=		{id=728,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thunderbolt"]=		{id=736,		ParentGroup=MAP_SPELL_DEFAULT},
	["Harden Shell"]=		{id=737,		ParentGroup=MAP_SPELL_DEFAULT},
	["Absolute Terror"]=	{id=738,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Gates of Hades"]=		{id=739,		ParentGroup=MAP_SPELL_DEFAULT},
	["Tourbillion"]=		{id=740,		ParentGroup=MAP_SPELL_DEFAULT},
	["Pyric Bulwark"]=		{id=741,		ParentGroup=MAP_SPELL_DEFAULT},
	["Bilgestorm"]=			{id=742,		ParentGroup=MAP_SPELL_DEFAULT},
	["Bloodrake"]=			{id=743,		ParentGroup=MAP_SPELL_DEFAULT},
	["Droning Whirlwind"]=	{id=744,		ParentGroup=MAP_SPELL_DEFAULT},
	["Carcharian Verve"]=	{id=745,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blistering Roar"]=	{id=746,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Uproot"]=				{id=747,		ParentGroup=MAP_SPELL_DEFAULT},
	["Crashing Thunder"]=	{id=748,		ParentGroup=MAP_SPELL_DEFAULT},
	["Polar Roar"]=			{id=749,		ParentGroup=MAP_SPELL_DEFAULT},
	["Mighty Guard"]=		{id=750,		ParentGroup=MAP_SPELL_DEFAULT},
	["Cruel Joke"]=			{id=751,		ParentGroup=MAP_SKILL_ENFEEBLING},
	["Cesspool"]=			{id=752,		ParentGroup=MAP_SPELL_DEFAULT},
	["Tearing Gust"]=		{id=753,		ParentGroup=MAP_SPELL_DEFAULT},
	["Indi-Regen"]=			{id=768,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Poison"]=		{id=769,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Refresh"]=		{id=770,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Haste"]=			{id=771,		ParentGroup=MAP_SPELL_INDI},
	["Indi-STR"]=			{id=772,		ParentGroup=MAP_SPELL_INDI},
	["Indi-DEX"]=			{id=773,		ParentGroup=MAP_SPELL_INDI},
	["Indi-VIT"]=			{id=774,		ParentGroup=MAP_SPELL_INDI},
	["Indi-AGI"]=			{id=775,		ParentGroup=MAP_SPELL_INDI},
	["Indi-INT"]=			{id=776,		ParentGroup=MAP_SPELL_INDI},
	["Indi-MND"]=			{id=777,		ParentGroup=MAP_SPELL_INDI},
	["Indi-CHR"]=			{id=778,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Fury"]=			{id=779,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Barrier"]=		{id=780,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Acumen"]=		{id=781,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Fend"]=			{id=782,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Precision"]=		{id=783,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Voidance"]=		{id=784,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Focus"]=			{id=785,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Attunement"]=	{id=786,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Wilt"]=			{id=787,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Frailty"]=		{id=788,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Fade"]=			{id=789,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Malaise"]=		{id=790,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Slip"]=			{id=791,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Torpor"]=		{id=792,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Vex"]=			{id=793,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Languor"]=		{id=794,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Slow"]=			{id=795,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Paralysis"]=		{id=796,		ParentGroup=MAP_SPELL_INDI},
	["Indi-Gravity"]=		{id=797,		ParentGroup=MAP_SPELL_INDI},
	["Geo-Regen"]=			{id=798,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Poison"]=			{id=799,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Refresh"]=		{id=800,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Haste"]=			{id=801,		ParentGroup=MAP_SPELL_GEO},
	["Geo-STR"]=			{id=802,		ParentGroup=MAP_SPELL_GEO},
	["Geo-DEX"]=			{id=803,		ParentGroup=MAP_SPELL_GEO},
	["Geo-VIT"]=			{id=804,		ParentGroup=MAP_SPELL_GEO},
	["Geo-AGI"]=			{id=805,		ParentGroup=MAP_SPELL_GEO},
	["Geo-INT"]=			{id=806,		ParentGroup=MAP_SPELL_GEO},
	["Geo-MND"]=			{id=807,		ParentGroup=MAP_SPELL_GEO},
	["Geo-CHR"]=			{id=808,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Fury"]=			{id=809,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Barrier"]=		{id=810,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Acumen"]=			{id=811,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Fend"]=			{id=812,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Precision"]=		{id=813,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Voidance"]=		{id=814,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Focus"]=			{id=815,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Attunement"]=		{id=816,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Wilt"]=			{id=817,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Frailty"]=		{id=818,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Fade"]=			{id=819,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Malaise"]=		{id=820,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Slip"]=			{id=821,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Torpor"]=			{id=822,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Vex"]=			{id=823,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Languor"]=		{id=824,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Slow"]=			{id=825,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Paralysis"]=		{id=826,		ParentGroup=MAP_SPELL_GEO},
	["Geo-Gravity"]=		{id=827,		ParentGroup=MAP_SPELL_GEO},
	["Fira"]=			{id=828,		ParentGroup=MAP_SPELL_DEFAULT},
	["Fira II"]=		{id=829,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blizzara"]=		{id=830,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blizzara II"]=	{id=831,		ParentGroup=MAP_SPELL_DEFAULT},
	["Aera"]=			{id=832,		ParentGroup=MAP_SPELL_DEFAULT},
	["Aera II"]=		{id=833,		ParentGroup=MAP_SPELL_DEFAULT},
	["Stonera"]=		{id=834,		ParentGroup=MAP_SPELL_DEFAULT},
	["Stonera II"]=		{id=835,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thundara"]=		{id=836,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thundara II"]=	{id=837,		ParentGroup=MAP_SPELL_DEFAULT},
	["Watera"]=			{id=838,		ParentGroup=MAP_SPELL_DEFAULT},
	["Watera II"]=		{id=839,		ParentGroup=MAP_SPELL_DEFAULT},
	["Foil"]=			{id=840,		ParentGroup=MAP_SPELL_DEFAULT},
	["Distract"]=		{id=841,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Distract II"]=	{id=842,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Frazzle"]=		{id=843,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Frazzle II"]=		{id=844,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Flurry"]=			{id=845,		ParentGroup=MAP_SPELL_FLURRY},
	["Flurry II"]=		{id=846,		ParentGroup=MAP_SPELL_FLURRY},
	["Atomos"]=			{id=847,		ParentGroup=MAP_SPELL_AVATAR},
	["Reraise IV"]=		{id=848,		ParentGroup=MAP_SPELL_RERAISE},
	["Fire VI"]=		{id=849,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blizzard VI"]=	{id=850,		ParentGroup=MAP_SPELL_DEFAULT},
	["Aero VI"]=		{id=851,		ParentGroup=MAP_SPELL_DEFAULT},
	["Stone VI"]=		{id=852,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thunder VI"]=		{id=853,		ParentGroup=MAP_SPELL_DEFAULT},
	["Water VI"]=		{id=854,		ParentGroup=MAP_SPELL_DEFAULT},
	["Enlight II"]=		{id=855,		ParentGroup=MAP_SPELL_ENLIGHT},
	["Endark II"]=		{id=856,		ParentGroup=MAP_SPELL_ENDARK},
	["Sandstorm II"]=	{id=857,		ParentGroup=MAP_SPELL_STORM},
	["Rainstorm II"]=	{id=858,		ParentGroup=MAP_SPELL_STORM},
	["Windstorm II"]=	{id=859,		ParentGroup=MAP_SPELL_STORM},
	["Firestorm II"]=	{id=860,		ParentGroup=MAP_SPELL_STORM},
	["Hailstorm II"]=	{id=861,		ParentGroup=MAP_SPELL_STORM},
	["Thunderstorm II"]={id=862,		ParentGroup=MAP_SPELL_STORM},
	["Voidstorm II"]=	{id=863,		ParentGroup=MAP_SPELL_STORM},
	["Aurorastorm II"]=	{id=864,		ParentGroup=MAP_SPELL_STORM},
	["Fira III"]=		{id=865,		ParentGroup=MAP_SPELL_DEFAULT},
	["Blizzara III"]=	{id=866,		ParentGroup=MAP_SPELL_DEFAULT},
	["Aera III"]=		{id=867,		ParentGroup=MAP_SPELL_DEFAULT},
	["Stonera III"]=	{id=868,		ParentGroup=MAP_SPELL_DEFAULT},
	["Thundara III"]=	{id=869,		ParentGroup=MAP_SPELL_DEFAULT},
	["Watera III"]=		{id=870,		ParentGroup=MAP_SPELL_DEFAULT},
	["Fire Threnody II"]=		{id=871,		ParentGroup=MAP_SPELL_THRENODY},
	["Ice Threnody II"]=		{id=872,		ParentGroup=MAP_SPELL_THRENODY},
	["Wind Threnody II"]=		{id=873,		ParentGroup=MAP_SPELL_THRENODY},
	["Earth Threnody II"]=		{id=874,		ParentGroup=MAP_SPELL_THRENODY},
	["Ltng. Threnody II"]=		{id=875,		ParentGroup=MAP_SPELL_THRENODY},
	["Water Threnody II"]=		{id=876,		ParentGroup=MAP_SPELL_THRENODY},
	["Light Threnody II"]=		{id=877,		ParentGroup=MAP_SPELL_THRENODY},
	["Dark Threnody II"]=		{id=878,		ParentGroup=MAP_SPELL_THRENODY},
	["Inundation"]=		{id=879,		ParentGroup=MAP_ENFEEBLE_DURATION},
	["Drain III"]=		{id=880,		ParentGroup=MAP_SPELL_DRAIN},
	["Aspir III"]=		{id=881,		ParentGroup=MAP_SPELL_ASPIR},
	["Distract III"]=	{id=882,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Frazzle III"]=	{id=883,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Addle II"]=		{id=884,		ParentGroup=MAP_ENFEEBLE_POTENCY},
	["Geohelix II"]=	{id=885,		ParentGroup=MAP_SPELL_HELIX},
	["Hydrohelix II"]=	{id=886,		ParentGroup=MAP_SPELL_HELIX},
	["Anemohelix II"]=	{id=887,		ParentGroup=MAP_SPELL_HELIX},
	["Pyrohelix II"]=	{id=888,		ParentGroup=MAP_SPELL_HELIX},
	["Cryohelix II"]=	{id=889,		ParentGroup=MAP_SPELL_HELIX},
	["Ionohelix II"]=	{id=890,		ParentGroup=MAP_SPELL_HELIX},
	["Noctohelix II"]=	{id=891,		ParentGroup=MAP_SPELL_HELIX},
	["Luminohelix II"]=	{id=892,		ParentGroup=MAP_SPELL_HELIX},
	["Full Cure"]=		{id=893,		ParentGroup=MAP_SPELL_CURE},
	["Refresh III"]=	{id=894,		ParentGroup=MAP_SPELL_REFRESH},
	["Temper II"]=		{id=895,		ParentGroup=MAP_SPELL_TEMPER},
	["Shantotto"]=		{id=896,		ParentGroup=MAP_SPELL_TRUST},
	["Naji"]=			{id=897,		ParentGroup=MAP_SPELL_TRUST},
	["Kupipi"]=			{id=898,		ParentGroup=MAP_SPELL_TRUST},
	["Excenmille"]=		{id=899,		ParentGroup=MAP_SPELL_TRUST},
	["Ayame"]=			{id=900,		ParentGroup=MAP_SPELL_TRUST},
	["Nanaa Mihgo"]=	{id=901,		ParentGroup=MAP_SPELL_TRUST},
	["Curilla"]=		{id=902,		ParentGroup=MAP_SPELL_TRUST},
	["Volker"]=			{id=903,		ParentGroup=MAP_SPELL_TRUST},
	["Ajido-Marujido"]=	{id=904,		ParentGroup=MAP_SPELL_TRUST},
	["Trion"]=			{id=905,		ParentGroup=MAP_SPELL_TRUST},
	["Zeid"]=			{id=906,		ParentGroup=MAP_SPELL_TRUST},
	["Lion"]=			{id=907,		ParentGroup=MAP_SPELL_TRUST},
	["Tenzen"]=			{id=908,		ParentGroup=MAP_SPELL_TRUST},
	["Mihli Aliapoh"]=	{id=909,		ParentGroup=MAP_SPELL_TRUST},
	["Valaineral"]=		{id=910,		ParentGroup=MAP_SPELL_TRUST},
	["Joachim"]=		{id=911,		ParentGroup=MAP_SPELL_TRUST},
	["Naja Salaheem"]=	{id=912,		ParentGroup=MAP_SPELL_TRUST},
	["Prishe"]=			{id=913,		ParentGroup=MAP_SPELL_TRUST},
	["Ulmia"]=			{id=914,		ParentGroup=MAP_SPELL_TRUST},
	["Shikaree Z"]=		{id=915,		ParentGroup=MAP_SPELL_TRUST},
	["Cherukiki"]=		{id=916,		ParentGroup=MAP_SPELL_TRUST},
	["Iron Eater"]=		{id=917,		ParentGroup=MAP_SPELL_TRUST},
	["Gessho"]=			{id=918,		ParentGroup=MAP_SPELL_TRUST},
	["Gadalar"]=		{id=919,		ParentGroup=MAP_SPELL_TRUST},
	["Rainemard"]=		{id=920,		ParentGroup=MAP_SPELL_TRUST},
	["Ingrid"]=			{id=921,		ParentGroup=MAP_SPELL_TRUST},
	["Lehko Habhoka"]=	{id=922,		ParentGroup=MAP_SPELL_TRUST},
	["Nashmeira"]=		{id=923,		ParentGroup=MAP_SPELL_TRUST},
	["Zazarg"]=			{id=924,		ParentGroup=MAP_SPELL_TRUST},
	["Ovjang"]=			{id=925,		ParentGroup=MAP_SPELL_TRUST},
	["Mnejing"]=		{id=926,		ParentGroup=MAP_SPELL_TRUST},
	["Sakura"]=			{id=927,		ParentGroup=MAP_SPELL_TRUST},
	["Luzaf"]=			{id=928,		ParentGroup=MAP_SPELL_TRUST},
	["Najelith"]=		{id=929,		ParentGroup=MAP_SPELL_TRUST},
	["Aldo"]=			{id=930,		ParentGroup=MAP_SPELL_TRUST},
	["Moogle"]=			{id=931,		ParentGroup=MAP_SPELL_TRUST},
	["Fablinix"]=		{id=932,		ParentGroup=MAP_SPELL_TRUST},
	["Maat"]=			{id=933,		ParentGroup=MAP_SPELL_TRUST},
	["D. Shantotto"]=	{id=934,		ParentGroup=MAP_SPELL_TRUST},
	["Star Sibyl"]=		{id=935,		ParentGroup=MAP_SPELL_TRUST},
	["Karaha-Baruha"]=	{id=936,		ParentGroup=MAP_SPELL_TRUST},
	["Cid"]=			{id=937,		ParentGroup=MAP_SPELL_TRUST},
	["Gilgamesh"]=		{id=938,		ParentGroup=MAP_SPELL_TRUST},
	["Areuhat"]=		{id=939,		ParentGroup=MAP_SPELL_TRUST},
	["Semih Lafihna"]=	{id=940,		ParentGroup=MAP_SPELL_TRUST},
	["Elivira"]=		{id=941,		ParentGroup=MAP_SPELL_TRUST},
	["Noillurie"]=		{id=942,		ParentGroup=MAP_SPELL_TRUST},
	["Lhu Mhakaracca"]=	{id=943,		ParentGroup=MAP_SPELL_TRUST},
	["Ferreous Coffin"]={id=944,		ParentGroup=MAP_SPELL_TRUST},
	["Lilisette"]=		{id=945,		ParentGroup=MAP_SPELL_TRUST},
	["Mumor"]=			{id=946,		ParentGroup=MAP_SPELL_TRUST},
	["Uka Totlihn"]=	{id=947,		ParentGroup=MAP_SPELL_TRUST},
	["Klara"]=			{id=948,		ParentGroup=MAP_SPELL_TRUST},
	["Romaa Mihgo"]=	{id=949,		ParentGroup=MAP_SPELL_TRUST},
	["Kuyin Hathdenna"]={id=950,		ParentGroup=MAP_SPELL_TRUST},
	["Rahal"]=			{id=951,		ParentGroup=MAP_SPELL_TRUST},
	["Koru-Moru"]=		{id=952,		ParentGroup=MAP_SPELL_TRUST},
	["Pieuje (UC)"]=	{id=953,		ParentGroup=MAP_SPELL_TRUST},
	["I. Shield (UC)"]=	{id=954,		ParentGroup=MAP_SPELL_TRUST},
	["Apururu (UC)"]=	{id=955,		ParentGroup=MAP_SPELL_TRUST},
	["Jakoh (UC)"]=		{id=956,		ParentGroup=MAP_SPELL_TRUST},
	["Flaviria (UC)"]=	{id=957,		ParentGroup=MAP_SPELL_TRUST},
	["Babban"]=			{id=958,		ParentGroup=MAP_SPELL_TRUST},
	["Abenzio"]=		{id=959,		ParentGroup=MAP_SPELL_TRUST},
	["Rughadjeen"]=		{id=960,		ParentGroup=MAP_SPELL_TRUST},
	["Kukki-Chebukki"]=	{id=961,		ParentGroup=MAP_SPELL_TRUST},
	["Margret"]=		{id=962,		ParentGroup=MAP_SPELL_TRUST},
	["Chacharoon"]=		{id=963,		ParentGroup=MAP_SPELL_TRUST},
	["Lhe Lhangavo"]=	{id=964,		ParentGroup=MAP_SPELL_TRUST},
	["Arciela"]=		{id=965,		ParentGroup=MAP_SPELL_TRUST},
	["Mayakov"]=		{id=966,		ParentGroup=MAP_SPELL_TRUST},
	["Qultada"]=		{id=967,		ParentGroup=MAP_SPELL_TRUST},
	["Adelheid"]=		{id=968,		ParentGroup=MAP_SPELL_TRUST},
	["Amchuchu"]=		{id=969,		ParentGroup=MAP_SPELL_TRUST},
	["Brygid"]=			{id=970,		ParentGroup=MAP_SPELL_TRUST},
	["Mildaurion"]=		{id=971,		ParentGroup=MAP_SPELL_TRUST},
	["Halver"]=			{id=972,		ParentGroup=MAP_SPELL_TRUST},
	["Rongelouts"]=		{id=973,		ParentGroup=MAP_SPELL_TRUST},
	["Leonoyne"]=		{id=974,		ParentGroup=MAP_SPELL_TRUST},
	["Maximilian"]=		{id=975,		ParentGroup=MAP_SPELL_TRUST},
	["Kayeel-Payeel"]=	{id=976,		ParentGroup=MAP_SPELL_TRUST},
	["Robel-Akbel"]=	{id=977,		ParentGroup=MAP_SPELL_TRUST},
	["Kupofried"]=		{id=978,		ParentGroup=MAP_SPELL_TRUST},
	["Selh'teus"]=		{id=979,		ParentGroup=MAP_SPELL_TRUST},
	["Yoran-Oran (UC)"]={id=980,		ParentGroup=MAP_SPELL_TRUST},
	["Sylvie (UC)"]=	{id=981,		ParentGroup=MAP_SPELL_TRUST},
	["Abquhbah"]=		{id=982,		ParentGroup=MAP_SPELL_TRUST},
	["Balamor"]=		{id=983,		ParentGroup=MAP_SPELL_TRUST},
	["August"]=			{id=984,		ParentGroup=MAP_SPELL_TRUST},
	["Rosulatia"]=		{id=985,		ParentGroup=MAP_SPELL_TRUST},
	["Teodor"]=			{id=986,		ParentGroup=MAP_SPELL_TRUST},
	["Ullegore"]=		{id=987,		ParentGroup=MAP_SPELL_TRUST},
	["Makki-Chebukki"]=	{id=988,		ParentGroup=MAP_SPELL_TRUST},
	["King of Hearts"]=	{id=989,		ParentGroup=MAP_SPELL_TRUST},
	["Morimar"]=		{id=990,		ParentGroup=MAP_SPELL_TRUST},
	["Darrcuiln"]=		{id=991,		ParentGroup=MAP_SPELL_TRUST},
	["AAHM"]=			{id=992,		ParentGroup=MAP_SPELL_TRUST},
	["AAEV"]=			{id=993,		ParentGroup=MAP_SPELL_TRUST},
	["AAMR"]=			{id=994,		ParentGroup=MAP_SPELL_TRUST},
	["AATT"]=			{id=995,		ParentGroup=MAP_SPELL_TRUST},
	["AAGK"]=			{id=996,		ParentGroup=MAP_SPELL_TRUST},
	["Iroha"]=			{id=997,		ParentGroup=MAP_SPELL_TRUST},
	["Ygnas"]=			{id=998,		ParentGroup=MAP_SPELL_TRUST},
	["Monberaux"]=		{id=999,		ParentGroup=MAP_SPELL_TRUST},
	["Cornelia"]=		{id=1002,		ParentGroup=MAP_SPELL_TRUST},
	["Matsui-P"]=		{id=1003,		ParentGroup=MAP_SPELL_TRUST},
	["Excenmille [S]"]=	{id=1004,		ParentGroup=MAP_SPELL_TRUST},
	["Ayame (UC)"]=		{id=1005,		ParentGroup=MAP_SPELL_TRUST},
	["Maat (UC)"]=		{id=1006,		ParentGroup=MAP_SPELL_TRUST},
	["Aldo (UC)"]=		{id=1007,		ParentGroup=MAP_SPELL_TRUST},
	["Naja (UC)"]=		{id=1008,		ParentGroup=MAP_SPELL_TRUST},
	["Lion II"]=		{id=1009,		ParentGroup=MAP_SPELL_TRUST},
	["Zeid II"]=		{id=1010,		ParentGroup=MAP_SPELL_TRUST},
	["Prishe II"]=		{id=1011,		ParentGroup=MAP_SPELL_TRUST},
	["Nashmeira II"]=	{id=1012,		ParentGroup=MAP_SPELL_TRUST},
	["Lilisette II"]=	{id=1013,		ParentGroup=MAP_SPELL_TRUST},
	["Tenzen II"]=		{id=1014,		ParentGroup=MAP_SPELL_TRUST},
	["Mumor II"]=		{id=1015,		ParentGroup=MAP_SPELL_TRUST},
	["Ingrid II"]=		{id=1016,		ParentGroup=MAP_SPELL_TRUST},
	["Arciela II"]=		{id=1017,		ParentGroup=MAP_SPELL_TRUST},
	["Iroha II"]=		{id=1018,		ParentGroup=MAP_SPELL_TRUST},
	["Shantotto II"]=	{id=1019,		ParentGroup=MAP_SPELL_TRUST},
}