_G[MAP_WS] = {
	["Combo"]=				{id=1,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Shoulder Tackle"]=	{id=2,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["One Inch Punch"]=		{id=3,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Backhand Blow"]=		{id=4,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Raging Fists"]=		{id=5,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Spinning Attack"]=	{id=6,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Howling Fist"]=		{id=7,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Dragon Kick"]=		{id=8,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Asuran Fists"]=		{id=9,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Final Heaven"]=		{id=10,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Ascetic's Fury"]=		{id=11,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Stringing Pummel"]=	{id=12,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tornado Kick"]=		{id=13,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Victory Smite"]=		{id=14,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Shijin Spiral"]=		{id=15,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Wasp Sting"]=			{id=16,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Viper Bite"]=			{id=17,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Shadowstitch"]=		{id=18,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Gust Slash"]=			{id=19,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Cyclone"]=			{id=20,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Energy Steal"]=		{id=21,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Energy Drain"]=		{id=22,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Dancing Edge"]=		{id=23,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Shark Bite"]=			{id=24,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Evisceration"]=		{id=25,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Mercy Stroke"]=		{id=26,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Mandalic Stab"]=		{id=27,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Mordant Rime"]=		{id=28,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Pyrrhic Kleos"]=		{id=29,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Aeolian Edge"]=		{id=30,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Rudra's Storm"]=		{id=31,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Fast Blade"]=			{id=32,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Burning Blade"]=		{id=33,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Red Lotus Blade"]=	{id=34,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Flat Blade"]=			{id=35,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Shining Blade"]=		{id=36,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Seraph Blade"]=		{id=37,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Circle Blade"]=		{id=38,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Spirits Within"]=		{id=39,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Vorpal Blade"]=		{id=40,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Swift Blade"]=		{id=41,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Savage Blade"]=		{id=42,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Knights of Round"]=	{id=43,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Death Blossom"]=		{id=44,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Atonement"]=			{id=45,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Expiacion"]=			{id=46,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Sanguine Blade"]=		{id=47,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Hard Slash"]=			{id=48,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Power Slash"]=		{id=49,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Frostbite"]=			{id=50,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Freezebite"]=			{id=51,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Shockwave"]=			{id=52,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Crescent Moon"]=		{id=53,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Sickle Moon"]=		{id=54,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Spinning Slash"]=		{id=55,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Ground Strike"]=		{id=56,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Scourge"]=			{id=57,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Herculean Slash"]=	{id=58,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Torcleaver"]=			{id=59,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Resolution"]=			{id=60,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Dimidiation"]=		{id=61,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Fimbulvetr"]=			{id=62,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Raging Axe"]=			{id=64,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Smash Axe"]=			{id=65,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Gale Axe"]=			{id=66,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Avalanche Axe"]=		{id=67,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Spinning Axe"]=		{id=68,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Rampage"]=			{id=69,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Calamity"]=			{id=70,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Mistral Axe"]=		{id=71,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Decimation"]=			{id=72,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Onslaught"]=			{id=73,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Primal Rend"]=		{id=74,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Bora Axe"]=			{id=75,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Cloudsplitter"]=		{id=76,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Ruinator"]=			{id=77,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Blitz"]=				{id=78,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Shield Break"]=		{id=80,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Iron Tempest"]=		{id=81,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Sturmwind"]=			{id=82,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Armor Break"]=		{id=83,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Keen Edge"]=			{id=84,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Weapon Break"]=		{id=85,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Raging Rush"]=		{id=86,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Full Break"]=			{id=87,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Steel Cyclone"]=		{id=88,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Metatron Torment"]=	{id=89,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["King's Justice"]=		{id=90,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Fell Cleave"]=		{id=91,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Ukko's Fury"]=		{id=92,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Upheaval"]=			{id=93,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Disaster"]=			{id=94,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Slice"]=				{id=96,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Dark Harvest"]=		{id=97,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Shadow of Death"]=	{id=98,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Nightmare Scythe"]=	{id=99,		Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Spinning Scythe"]=	{id=100,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Vorpal Scythe"]=		{id=101,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Guillotine"]=			{id=102,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Cross Reaper"]=		{id=103,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Spiral Hell"]=		{id=104,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Catastrophe"]=		{id=105,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Insurgency"]=			{id=106,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Infernal Scythe"]=	{id=107,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Quietus"]=			{id=108,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Entropy"]=			{id=109,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Origin"]=				{id=110,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Double Thrust"]=		{id=112,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Thunder Thrust"]=		{id=113,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Raiden Thrust"]=		{id=114,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Leg Sweep"]=			{id=115,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Penta Thrust"]=		{id=116,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Vorpal Thrust"]=		{id=117,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Skewer"]=				{id=118,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Wheeling Thrust"]=	{id=119,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Impulse Drive"]=		{id=120,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Geirskogul"]=			{id=121,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Drakesbane"]=			{id=122,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Sonic Thrust"]=		{id=123,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Camlann's Torment"]=	{id=124,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Stardiver"]=			{id=125,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Diarmuid"]=			{id=126,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Blade: Rin"]=			{id=128,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Blade: Retsu"]=		{id=129,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Blade: Teki"]=		{id=130,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_HYBRID,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Blade: To"]=			{id=131,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_HYBRID,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Blade: Chi"]=			{id=132,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_HYBRID,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Blade: Ei"]=			{id=133,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Blade: Jin"]=			{id=134,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Blade: Ten"]=			{id=135,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Blade: Ku"]=			{id=136,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Blade: Metsu"]=		{id=137,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Blade: Kamu"]=		{id=138,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Blade: Yu"]=			{id=139,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Blade: Hi"]=			{id=140,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Blade: Shun"]=		{id=141,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Zesho Meppo"]=		{id=142,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tachi: Enpi"]=		{id=144,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tachi: Hobaku"]=		{id=145,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tachi: Goten"]=		{id=146,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_HYBRID,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tachi: Kagero"]=		{id=147,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_HYBRID,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tachi: Jinpu"]=		{id=148,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_HYBRID,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tachi: Koki"]=		{id=149,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_HYBRID,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tachi: Yukikaze"]=	{id=150,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tachi: Gekko"]=		{id=151,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tachi: Kasha"]=		{id=152,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tachi: Kaiten"]=		{id=153,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tachi: Rana"]=		{id=154,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tachi: Ageha"]=		{id=155,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tachi: Fudo"]=		{id=156,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tachi: Shoha"]=		{id=157,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tachi: Suikawari"]=	{id=158,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tachi: Mumei"]=		{id=159,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Shining Strike"]=		{id=160,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Seraph Strike"]=		{id=161,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Brainshaker"]=		{id=162,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Starlight"]=			{id=163,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Moonlight"]=			{id=164,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Skullbreaker"]=		{id=165,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["True Strike"]=		{id=166,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Judgment"]=			{id=167,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Hexa Strike"]=		{id=168,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Black Halo"]=			{id=169,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Randgrith"]=			{id=170,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Mystic Boon"]=		{id=171,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Flash Nova"]=			{id=172,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Dagan"]=				{id=173,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Realmrazer"]=			{id=174,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Exudation"]=			{id=175,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Heavy Swing"]=		{id=176,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Rock Crusher"]=		{id=177,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Earth Crusher"]=		{id=178,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Starburst"]=			{id=179,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Sunburst"]=			{id=180,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Shell Crusher"]=		{id=181,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Full Swing"]=			{id=182,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Spirit Taker"]=		{id=183,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Retribution"]=		{id=184,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Gate of Tartarus"]=	{id=185,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Vidohunir"]=			{id=186,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Garland of Bliss"]=	{id=187,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Omniscience"]=		{id=188,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Cataclysm"]=			{id=189,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Myrkr"]=				{id=190,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Shattersoul"]=		{id=191,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Flaming Arrow"]=		{id=192,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_HYBRID,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Piercing Arrow"]=		{id=193,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Dulling Arrow"]=		{id=194,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Sidewinder"]=			{id=196,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Blast Arrow"]=		{id=197,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Arching Arrow"]=		{id=198,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Empyreal Arrow"]=		{id=199,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Namas Arrow"]=		{id=200,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Refulgent Arrow"]=	{id=201,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Jishnu's Radiance"]=	{id=202,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Apex Arrow"]=			{id=203,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Sarv"]=				{id=204,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Hot Shot"]=			{id=208,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_HYBRID,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Split Shot"]=			{id=209,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Sniper Shot"]=		{id=210,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Slug Shot"]=			{id=212,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Blast Shot"]=			{id=213,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Heavy Shot"]=			{id=214,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Detonator"]=			{id=215,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Coronach"]=			{id=216,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Trueflight"]=			{id=217,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Leaden Salute"]=		{id=218,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Numbing Shot"]=		{id=219,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Wildfire"]=			{id=220,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_MAGICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Last Stand"]=			{id=221,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Terminus"]=			{id=222,	Range=MAP_WS_RANGED,	DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Exenterator"]=		{id=224,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Chant du Cygne"]=		{id=225,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Requiescat"]=			{id=226,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Knights of Rotund"]=	{id=227,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Final Paradise"]=		{id=228,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Fast Blade II"]=		{id=229,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Dragon Blow"]=		{id=230,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Maru Kala"]=			{id=231,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Ruthless Stroke"]=	{id=232,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Imperator"]=			{id=233,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Dagda"]=				{id=234,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Oshala"]=				{id=235,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Uriel Blade"]=		{id=238,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Glory Slash"]=		{id=239,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Tartarus Torpor"]=	{id=240,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Netherspikes"]=		{id=241,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Carnal Nightmare"]=	{id=242,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Aegis Schism"]=		{id=243,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Dancing Chains"]=		{id=244,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Barbed Crescent"]=	{id=245,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Shackled Fists"]=		{id=246,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Foxfire"]=			{id=247,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Grim Halo"]=			{id=248,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Netherspikes"]=		{id=249,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Carnal Nightmare"]=	{id=250,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Aegis Schism"]=		{id=251,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Dancing Chains"]=		{id=252,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Barbed Crescent"]=	{id=253,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Vulcan Shot"]=		{id=254,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false},
	["Dimensional Death"]=	{id=255,	Range=MAP_WS_MELEE,		DamageType=MAP_DAMAGE_PHYSICAL,		Critical=false,		TPScaling=false,	fTPReplicate=false}
}