_G[MAP_ZONES] = {
["Phanauet Channel"]=               {id=1,    IsTown=false,  IsAdoulin=false},
["Carpenters' Landing"]=            {id=2,    IsTown=false,  IsAdoulin=false},
["Manaclipper"]=                    {id=3,    IsTown=false,  IsAdoulin=false},
["Bibiki Bay"]=                     {id=4,    IsTown=false,  IsAdoulin=false},
["Uleguerand Range"]=               {id=5,    IsTown=false,  IsAdoulin=false},
["Bearclaw Pinnacle"]=              {id=6,    IsTown=false,  IsAdoulin=false},
["Attohwa Chasm"]=                  {id=7,    IsTown=false,  IsAdoulin=false},
["Boneyard Gully"]=                 {id=8,    IsTown=false,  IsAdoulin=false},
["Pso'Xja"]=                        {id=9,    IsTown=false,  IsAdoulin=false},
["The Shrouded Maw"]=               {id=10,   IsTown=false,  IsAdoulin=false},
["Oldton Movalpolos"]=              {id=11,   IsTown=false,  IsAdoulin=false},
["Newton Movalpolos"]=              {id=12,   IsTown=false,  IsAdoulin=false},
["Mine Shaft #2716"]=               {id=13,   IsTown=false,  IsAdoulin=false},
["Hall of Transference"]=           {id=14,   IsTown=false,  IsAdoulin=false},
["Abyssea - Konschtat"]=            {id=15,   IsTown=false,  IsAdoulin=false},
["Promyvion - Holla"]=              {id=16,   IsTown=false,  IsAdoulin=false},
["Spire of Holla"]=                 {id=17,   IsTown=false,  IsAdoulin=false},
["Promyvion - Dem"]=                {id=18,   IsTown=false,  IsAdoulin=false},
["Spire of Dem"]=                   {id=19,   IsTown=false,  IsAdoulin=false},
["Promyvion - Mea"]=                {id=20,   IsTown=false,  IsAdoulin=false},
["Spire of Mea"]=                   {id=21,   IsTown=false,  IsAdoulin=false},
["Promyvion - Vahzl"]=              {id=22,   IsTown=false,  IsAdoulin=false},
["Spire of Vahzl"]=                 {id=23,   IsTown=false,  IsAdoulin=false},
["Lufaise Meadows"]=                {id=24,   IsTown=false,  IsAdoulin=false},
["Misareaux Coast"]=                {id=25,   IsTown=false,  IsAdoulin=false},
["Tavnazian Safehold"]=             {id=26,   IsTown=true ,  IsAdoulin=false},
["Phomiuna Aqueducts"]=             {id=27,   IsTown=false,  IsAdoulin=false},
["Sacrarium"]=                      {id=28,   IsTown=false,  IsAdoulin=false},
["Riverne - Site #B01"]=            {id=29,   IsTown=false,  IsAdoulin=false},
["Riverne - Site #A01"]=            {id=30,   IsTown=false,  IsAdoulin=false},
["Monarch Linn"]=                   {id=31,   IsTown=false,  IsAdoulin=false},
["Sealion's Den"]=                  {id=32,   IsTown=false,  IsAdoulin=false},
["Al'Taieu"]=                       {id=33,   IsTown=false,  IsAdoulin=false},
["Grand Palace of Hu'Xzoi"]=        {id=34,   IsTown=false,  IsAdoulin=false},
["The Garden of Ru'Hmet"]=          {id=35,   IsTown=false,  IsAdoulin=false},
["Empyreal Paradox"]=               {id=36,   IsTown=false,  IsAdoulin=false},
["Temenos"]=                        {id=37,   IsTown=false,  IsAdoulin=false},
["Apollyon"]=                       {id=38,   IsTown=false,  IsAdoulin=false},
["Dynamis - Valkurm"]=              {id=39,   IsTown=false,  IsAdoulin=false},
["Dynamis - Buburimu"]=             {id=40,   IsTown=false,  IsAdoulin=false},
["Dynamis - Qufim"]=                {id=41,   IsTown=false,  IsAdoulin=false},
["Dynamis - Tavnazia"]=             {id=42,   IsTown=false,  IsAdoulin=false},
["Diorama Abdhaljs-Ghelsba"]=       {id=43,   IsTown=false,  IsAdoulin=false},
["Abdhaljs Isle-Purgonorgo"]=       {id=44,   IsTown=false,  IsAdoulin=false},
["Abyssea - Tahrongi"]=             {id=45,   IsTown=false,  IsAdoulin=false},
["Open sea route to Al Zahbi"]=     {id=46,   IsTown=false,  IsAdoulin=false},
["Open sea route to Mhaura"]=       {id=47,   IsTown=false,  IsAdoulin=false},
["Al Zahbi"]=                       {id=48,   IsTown=true ,  IsAdoulin=false},
["Aht Urhgan Whitegate"]=           {id=50,   IsTown=true ,  IsAdoulin=false},
["Wajaom Woodlands"]=               {id=51,   IsTown=false,  IsAdoulin=false},
["Bhaflau Thickets"]=               {id=52,   IsTown=false,  IsAdoulin=false},
["Nashmau"]=                        {id=53,   IsTown=true ,  IsAdoulin=false},
["Arrapago Reef"]=                  {id=54,   IsTown=false,  IsAdoulin=false},
["Ilrusi Atoll"]=                   {id=55,   IsTown=false,  IsAdoulin=false},
["Periqia"]=                        {id=56,   IsTown=false,  IsAdoulin=false},
["Talacca Cove"]=                   {id=57,   IsTown=false,  IsAdoulin=false},
["Silver Sea route to Nashmau"]=    {id=58,   IsTown=false,  IsAdoulin=false},
["Silver Sea route to Al Zahbi"]=   {id=59,   IsTown=false,  IsAdoulin=false},
["The Ashu Talif"]=                 {id=60,   IsTown=false,  IsAdoulin=false},
["Mount Zhayolm"]=                  {id=61,   IsTown=false,  IsAdoulin=false},
["Halvung"]=                        {id=62,   IsTown=false,  IsAdoulin=false},
["Lebros Cavern"]=                  {id=63,   IsTown=false,  IsAdoulin=false},
["Navukgo Execution Chamber"]=      {id=64,   IsTown=false,  IsAdoulin=false},
["Mamook"]=                         {id=65,   IsTown=false,  IsAdoulin=false},
["Mamool Ja Training Grounds"]=     {id=66,   IsTown=false,  IsAdoulin=false},
["Jade Sepulcher"]=                 {id=67,   IsTown=false,  IsAdoulin=false},
["Aydeewa Subterrane"]=             {id=68,   IsTown=false,  IsAdoulin=false},
["Leujaoam Sanctum"]=               {id=69,   IsTown=false,  IsAdoulin=false},
["Chocobo Circuit"]=                {id=70,   IsTown=true ,  IsAdoulin=false},
["The Colosseum"]=                  {id=71,   IsTown=true ,  IsAdoulin=false},
["Alzadaal Undersea Ruins"]=        {id=72,   IsTown=false,  IsAdoulin=false},
["Zhayolm Remnants"]=               {id=73,   IsTown=false,  IsAdoulin=false},
["Arrapago Remnants"]=              {id=74,   IsTown=false,  IsAdoulin=false},
["Bhaflau Remnants"]=               {id=75,   IsTown=false,  IsAdoulin=false},
["Silver Sea Remnants"]=            {id=76,   IsTown=false,  IsAdoulin=false},
["Nyzul Isle"]=                     {id=77,   IsTown=false,  IsAdoulin=false},
["Hazhalm Testing Grounds"]=        {id=78,   IsTown=false,  IsAdoulin=false},
["Caedarva Mire"]=                  {id=79,   IsTown=false,  IsAdoulin=false},
["Southern San d'Oria [S]"]=        {id=80,   IsTown=true ,  IsAdoulin=false},
["East Ronfaure [S]"]=              {id=81,   IsTown=false,  IsAdoulin=false},
["Jugner Forest [S]"]=              {id=82,   IsTown=false,  IsAdoulin=false},
["Vunkerl Inlet [S]"]=              {id=83,   IsTown=false,  IsAdoulin=false},
["Batallia Downs [S]"]=             {id=84,   IsTown=false,  IsAdoulin=false},
["La Vaule [S]"]=                   {id=85,   IsTown=false,  IsAdoulin=false},
["Everbloom Hollow"]=               {id=86,   IsTown=false,  IsAdoulin=false},
["Bastok Markets [S]"]=             {id=87,   IsTown=true ,  IsAdoulin=false},
["North Gustaberg [S]"]=            {id=88,   IsTown=false,  IsAdoulin=false},
["Grauberg [S]"]=                   {id=89,   IsTown=false,  IsAdoulin=false},
["Pashhow Marshlands [S]"]=         {id=90,   IsTown=false,  IsAdoulin=false},
["Rolanberry Fields [S]"]=          {id=91,   IsTown=false,  IsAdoulin=false},
["Beadeaux [S]"]=                   {id=92,   IsTown=false,  IsAdoulin=false},
["Ruhotz Silvermines"]=             {id=93,   IsTown=false,  IsAdoulin=false},
["Windurst Waters [S]"]=            {id=94,   IsTown=true ,  IsAdoulin=false},
["West Sarutabaruta [S]"]=          {id=95,   IsTown=false,  IsAdoulin=false},
["Fort Karugo-Narugo [S]"]=         {id=96,   IsTown=false,  IsAdoulin=false},
["Meriphataud Mountains [S]"]=      {id=97,   IsTown=false,  IsAdoulin=false},
["Sauromugue Champaign [S]"]=       {id=98,   IsTown=false,  IsAdoulin=false},
["Castle Oztroja [S]"]=             {id=99,   IsTown=false,  IsAdoulin=false},
["West Ronfaure"]=                  {id=100,  IsTown=false,  IsAdoulin=false},
["East Ronfaure"]=                  {id=101,  IsTown=false,  IsAdoulin=false},
["La Theine Plateau"]=              {id=102,  IsTown=false,  IsAdoulin=false},
["Valkurm Dunes"]=                  {id=103,  IsTown=false,  IsAdoulin=false},
["Jugner Forest"]=                  {id=104,  IsTown=false,  IsAdoulin=false},
["Batallia Downs"]=                 {id=105,  IsTown=false,  IsAdoulin=false},
["North Gustaberg"]=                {id=106,  IsTown=false,  IsAdoulin=false},
["South Gustaberg"]=                {id=107,  IsTown=false,  IsAdoulin=false},
["Konschtat Highlands"]=            {id=108,  IsTown=false,  IsAdoulin=false},
["Pashhow Marshlands"]=             {id=109,  IsTown=false,  IsAdoulin=false},
["Rolanberry Fields"]=              {id=110,  IsTown=false,  IsAdoulin=false},
["Beaucedine Glacier"]=             {id=111,  IsTown=false,  IsAdoulin=false},
["Xarcabard"]=                      {id=112,  IsTown=false,  IsAdoulin=false},
["Cape Teriggan"]=                  {id=113,  IsTown=false,  IsAdoulin=false},
["Eastern Altepa Desert"]=          {id=114,  IsTown=false,  IsAdoulin=false},
["West Sarutabaruta"]=              {id=115,  IsTown=false,  IsAdoulin=false},
["East Sarutabaruta"]=              {id=116,  IsTown=false,  IsAdoulin=false},
["Tahrongi Canyon"]=                {id=117,  IsTown=false,  IsAdoulin=false},
["Buburimu Peninsula"]=             {id=118,  IsTown=false,  IsAdoulin=false},
["Meriphataud Mountains"]=          {id=119,  IsTown=false,  IsAdoulin=false},
["Sauromugue Champaign"]=           {id=120,  IsTown=false,  IsAdoulin=false},
["The Sanctuary of Zi'Tah"]=        {id=121,  IsTown=false,  IsAdoulin=false},
["Ro'Maeve"]=                       {id=122,  IsTown=false,  IsAdoulin=false},
["Yuhtunga Jungle"]=                {id=123,  IsTown=false,  IsAdoulin=false},
["Yhoator Jungle"]=                 {id=124,  IsTown=false,  IsAdoulin=false},
["Western Altepa Desert"]=          {id=125,  IsTown=false,  IsAdoulin=false},
["Qufim Island"]=                   {id=126,  IsTown=false,  IsAdoulin=false},
["Behemoth's Dominion"]=            {id=127,  IsTown=false,  IsAdoulin=false},
["Valley of Sorrows"]=              {id=128,  IsTown=false,  IsAdoulin=false},
["Ghoyu's Reverie"]=                {id=129,  IsTown=false,  IsAdoulin=false},
["Ru'Aun Gardens"]=                 {id=130,  IsTown=false,  IsAdoulin=false},
["Mordion Gaol"]=                   {id=131,  IsTown=false,  IsAdoulin=false},
["Abyssea - La Theine"]=            {id=132,  IsTown=false,  IsAdoulin=false},
["Outer Ra'Kaznar [U2]"]=           {id=133,  IsTown=false,  IsAdoulin=false},
["Dynamis - Beaucedine"]=           {id=134,  IsTown=false,  IsAdoulin=false},
["Dynamis - Xarcabard"]=            {id=135,  IsTown=false,  IsAdoulin=false},
["Beaucedine Glacier [S]"]=         {id=136,  IsTown=false,  IsAdoulin=false},
["Xarcabard [S]"]=                  {id=137,  IsTown=false,  IsAdoulin=false},
["Castle Zvahl Baileys [S]"]=       {id=138,  IsTown=false,  IsAdoulin=false},
["Horlais Peak"]=                   {id=139,  IsTown=false,  IsAdoulin=false},
["Ghelsba Outpost"]=                {id=140,  IsTown=false,  IsAdoulin=false},
["Fort Ghelsba"]=                   {id=141,  IsTown=false,  IsAdoulin=false},
["Yughott Grotto"]=                 {id=142,  IsTown=false,  IsAdoulin=false},
["Palborough Mines"]=               {id=143,  IsTown=false,  IsAdoulin=false},
["Waughroon Shrine"]=               {id=144,  IsTown=false,  IsAdoulin=false},
["Giddeus"]=                        {id=145,  IsTown=false,  IsAdoulin=false},
["Balga's Dais"]=                   {id=146,  IsTown=false,  IsAdoulin=false},
["Beadeaux"]=                       {id=147,  IsTown=false,  IsAdoulin=false},
["Qulun Dome"]=                     {id=148,  IsTown=false,  IsAdoulin=false},
["Davoi"]=                          {id=149,  IsTown=false,  IsAdoulin=false},
["Monastic Cavern"]=                {id=150,  IsTown=false,  IsAdoulin=false},
["Castle Oztroja"]=                 {id=151,  IsTown=false,  IsAdoulin=false},
["Altar Room"]=                     {id=152,  IsTown=false,  IsAdoulin=false},
["The Boyahda Tree"]=               {id=153,  IsTown=false,  IsAdoulin=false},
["Dragon's Aery"]=                  {id=154,  IsTown=false,  IsAdoulin=false},
["Castle Zvahl Keep [S]"]=          {id=155,  IsTown=false,  IsAdoulin=false},
["Throne Room [S]"]=                {id=156,  IsTown=false,  IsAdoulin=false},
["Middle Delkfutt's Tower"]=        {id=157,  IsTown=false,  IsAdoulin=false},
["Upper Delkfutt's Tower"]=         {id=158,  IsTown=false,  IsAdoulin=false},
["Temple of Uggalepih"]=            {id=159,  IsTown=false,  IsAdoulin=false},
["Den of Rancor"]=                  {id=160,  IsTown=false,  IsAdoulin=false},
["Castle Zvahl Baileys"]=           {id=161,  IsTown=false,  IsAdoulin=false},
["Castle Zvahl Keep"]=              {id=162,  IsTown=false,  IsAdoulin=false},
["Sacrificial Chamber"]=            {id=163,  IsTown=false,  IsAdoulin=false},
["Garlaige Citadel [S]"]=           {id=164,  IsTown=false,  IsAdoulin=false},
["Throne Room"]=                    {id=165,  IsTown=false,  IsAdoulin=false},
["Ranguemont Pass"]=                {id=166,  IsTown=false,  IsAdoulin=false},
["Bostaunieux Oubliette"]=          {id=167,  IsTown=false,  IsAdoulin=false},
["Chamber of Oracles"]=             {id=168,  IsTown=false,  IsAdoulin=false},
["Toraimarai Canal"]=               {id=169,  IsTown=false,  IsAdoulin=false},
["Full Moon Fountain"]=             {id=170,  IsTown=false,  IsAdoulin=false},
["Crawlers' Nest [S]"]=             {id=171,  IsTown=false,  IsAdoulin=false},
["Zeruhn Mines"]=                   {id=172,  IsTown=false,  IsAdoulin=false},
["Korroloka Tunnel"]=               {id=173,  IsTown=false,  IsAdoulin=false},
["Kuftal Tunnel"]=                  {id=174,  IsTown=false,  IsAdoulin=false},
["The Eldieme Necropolis [S]"]=     {id=175,  IsTown=false,  IsAdoulin=false},
["Sea Serpent Grotto"]=             {id=176,  IsTown=false,  IsAdoulin=false},
["Ve'Lugannon Palace"]=             {id=177,  IsTown=false,  IsAdoulin=false},
["The Shrine of Ru'Avitau"]=        {id=178,  IsTown=false,  IsAdoulin=false},
["Stellar Fulcrum"]=                {id=179,  IsTown=false,  IsAdoulin=false},
["La'Loff Amphitheater"]=           {id=180,  IsTown=false,  IsAdoulin=false},
["The Celestial Nexus"]=            {id=181,  IsTown=false,  IsAdoulin=false},
["Walk of Echoes"]=                 {id=182,  IsTown=false,  IsAdoulin=false},
["Maquette Abdhaljs-LegionA"]=      {id=183,  IsTown=false,  IsAdoulin=false},
["Lower Delkfutt's Tower"]=         {id=184,  IsTown=false,  IsAdoulin=false},
["Dynamis - San d'Oria"]=           {id=185,  IsTown=false,  IsAdoulin=false},
["Dynamis - Bastok"]=               {id=186,  IsTown=false,  IsAdoulin=false},
["Dynamis - Windurst"]=             {id=187,  IsTown=false,  IsAdoulin=false},
["Dynamis - Jeuno"]=                {id=188,  IsTown=false,  IsAdoulin=false},
["Outer Ra'Kaznar [U3]"]=           {id=189,  IsTown=false,  IsAdoulin=false},
["King Ranperre's Tomb"]=           {id=190,  IsTown=false,  IsAdoulin=false},
["Dangruf Wadi"]=                   {id=191,  IsTown=false,  IsAdoulin=false},
["Inner Horutoto Ruins"]=           {id=192,  IsTown=false,  IsAdoulin=false},
["Ordelle's Caves"]=                {id=193,  IsTown=false,  IsAdoulin=false},
["Outer Horutoto Ruins"]=           {id=194,  IsTown=false,  IsAdoulin=false},
["The Eldieme Necropolis"]=         {id=195,  IsTown=false,  IsAdoulin=false},
["Gusgen Mines"]=                   {id=196,  IsTown=false,  IsAdoulin=false},
["Crawlers' Nest"]=                 {id=197,  IsTown=false,  IsAdoulin=false},
["Maze of Shakhrami"]=              {id=198,  IsTown=false,  IsAdoulin=false},
["Garlaige Citadel"]=               {id=200,  IsTown=false,  IsAdoulin=false},
["Cloister of Gales"]=              {id=201,  IsTown=false,  IsAdoulin=false},
["Cloister of Storms"]=             {id=202,  IsTown=false,  IsAdoulin=false},
["Cloister of Frost"]=              {id=203,  IsTown=false,  IsAdoulin=false},
["Fei'Yin"]=                        {id=204,  IsTown=false,  IsAdoulin=false},
["Ifrit's Cauldron"]=               {id=205,  IsTown=false,  IsAdoulin=false},
["Qu'Bia Arena"]=                   {id=206,  IsTown=false,  IsAdoulin=false},
["Cloister of Flames"]=             {id=207,  IsTown=false,  IsAdoulin=false},
["Quicksand Caves"]=                {id=208,  IsTown=false,  IsAdoulin=false},
["Cloister of Tremors"]=            {id=209,  IsTown=false,  IsAdoulin=false},
["Cloister of Tides"]=              {id=211,  IsTown=false,  IsAdoulin=false},
["Gustav Tunnel"]=                  {id=212,  IsTown=false,  IsAdoulin=false},
["Labyrinth of Onzozo"]=            {id=213,  IsTown=false,  IsAdoulin=false},
["Abyssea - Attohwa"]=              {id=215,  IsTown=false,  IsAdoulin=false},
["Abyssea - Misareaux"]=            {id=216,  IsTown=false,  IsAdoulin=false},
["Abyssea - Vunkerl"]=              {id=217,  IsTown=false,  IsAdoulin=false},
["Abyssea - Altepa"]=               {id=218,  IsTown=false,  IsAdoulin=false},
["Ship bound for Selbina"]=         {id=220,  IsTown=false,  IsAdoulin=false},
["Ship bound for Mhaura"]=          {id=221,  IsTown=false,  IsAdoulin=false},
["Provenance"]=                     {id=222,  IsTown=false,  IsAdoulin=false},
["San d'Oria-Jeuno Airship"]=       {id=223,  IsTown=true ,  IsAdoulin=false},
["Bastok-Jeuno Airship"]=           {id=224,  IsTown=true ,  IsAdoulin=false},
["Windurst-Jeuno Airship"]=         {id=225,  IsTown=true ,  IsAdoulin=false},
["Kazham-Jeuno Airship"]=           {id=226,  IsTown=true ,  IsAdoulin=false},
["Ship bound for Selbina"]=         {id=227,  IsTown=false,  IsAdoulin=false},
["Ship bound for Mhaura"]=          {id=228,  IsTown=false,  IsAdoulin=false},
["Throne Room [V]"]=                {id=229,  IsTown=false,  IsAdoulin=false},
["Southern San d'Oria"]=            {id=230,  IsTown=true ,  IsAdoulin=false},
["Northern San d'Oria"]=            {id=231,  IsTown=true ,  IsAdoulin=false},
["Port San d'Oria"]=                {id=232,  IsTown=true ,  IsAdoulin=false},
["Chateau d'Oraguille"]=            {id=233,  IsTown=true ,  IsAdoulin=false},
["Bastok Mines"]=                   {id=234,  IsTown=true ,  IsAdoulin=false},
["Bastok Markets"]=                 {id=235,  IsTown=true ,  IsAdoulin=false},
["Port Bastok"]=                    {id=236,  IsTown=true ,  IsAdoulin=false},
["Metalworks"]=                     {id=237,  IsTown=true ,  IsAdoulin=false},
["Windurst Waters"]=                {id=238,  IsTown=true ,  IsAdoulin=false},
["Windurst Walls"]=                 {id=239,  IsTown=true ,  IsAdoulin=false},
["Port Windurst"]=                  {id=240,  IsTown=true ,  IsAdoulin=false},
["Windurst Woods"]=                 {id=241,  IsTown=true ,  IsAdoulin=false},
["Heavens Tower"]=                  {id=242,  IsTown=true ,  IsAdoulin=false},
["Ru'Lude Gardens"]=                {id=243,  IsTown=true ,  IsAdoulin=false},
["Upper Jeuno"]=                    {id=244,  IsTown=true ,  IsAdoulin=false},
["Lower Jeuno"]=                    {id=245,  IsTown=true ,  IsAdoulin=false},
["Port Jeuno"]=                     {id=246,  IsTown=true ,  IsAdoulin=false},
["Rabao"]=                          {id=247,  IsTown=true ,  IsAdoulin=false},
["Selbina"]=                        {id=248,  IsTown=true ,  IsAdoulin=false},
["Mhaura"]=                         {id=249,  IsTown=true ,  IsAdoulin=false},
["Kazham"]=                         {id=250,  IsTown=true ,  IsAdoulin=false},
["Hall of the Gods"]=               {id=251,  IsTown=false,  IsAdoulin=false},
["Norg"]=                           {id=252,  IsTown=true ,  IsAdoulin=false},
["Abyssea - Uleguerand"]=           {id=253,  IsTown=false,  IsAdoulin=false},
["Abyssea - Grauberg"]=             {id=254,  IsTown=false,  IsAdoulin=false},
["Abyssea - Empyreal Paradox"]=     {id=255,  IsTown=false,  IsAdoulin=false},
["Western Adoulin"]=                {id=256,  IsTown=true ,  IsAdoulin=true },
["Eastern Adoulin"]=                {id=257,  IsTown=true ,  IsAdoulin=true },
["Rala Waterways"]=                 {id=258,  IsTown=false,  IsAdoulin=true },
["Rala Waterways [U]"]=             {id=259,  IsTown=false,  IsAdoulin=true },
["Yahse Hunting Grounds"]=          {id=260,  IsTown=false,  IsAdoulin=true },
["Ceizak Battlegrounds"]=           {id=261,  IsTown=false,  IsAdoulin=true },
["Foret de Hennetiel"]=             {id=262,  IsTown=false,  IsAdoulin=true },
["Yorcia Weald"]=                   {id=263,  IsTown=false,  IsAdoulin=true },
["Yorcia Weald [U]"]=               {id=264,  IsTown=false,  IsAdoulin=true },
["Morimar Basalt Fields"]=          {id=265,  IsTown=false,  IsAdoulin=true },
["Marjami Ravine"]=                 {id=266,  IsTown=false,  IsAdoulin=true },
["Kamihr Drifts"]=                  {id=267,  IsTown=false,  IsAdoulin=true },
["Sih Gates"]=                      {id=268,  IsTown=false,  IsAdoulin=true },
["Moh Gates"]=                      {id=269,  IsTown=false,  IsAdoulin=true },
["Cirdas Caverns"]=                 {id=270,  IsTown=false,  IsAdoulin=true },
["Cirdas Caverns [U]"]=             {id=271,  IsTown=false,  IsAdoulin=true },
["Dho Gates"]=                      {id=272,  IsTown=false,  IsAdoulin=true },
["Woh Gates"]=                      {id=273,  IsTown=false,  IsAdoulin=true },
["Outer Ra'Kaznar"]=                {id=274,  IsTown=false,  IsAdoulin=true },
["Outer Ra'Kaznar [U1]"]=           {id=275,  IsTown=false,  IsAdoulin=true },
["Ra'Kaznar Inner Court"]=          {id=276,  IsTown=false,  IsAdoulin=true },
["Ra'Kaznar Turris"]=               {id=277,  IsTown=false,  IsAdoulin=true },
["Gwora - Corridor"]=               {id=278,  IsTown=false,  IsAdoulin=false},
["Walk of Echoes [P2]"]=            {id=279,  IsTown=false,  IsAdoulin=false},
["Mog Garden"]=                     {id=280,  IsTown=true ,  IsAdoulin=true },
["Leafallia"]=                      {id=281,  IsTown=true ,  IsAdoulin=true },
["Mount Kamihr"]=                   {id=282,  IsTown=false,  IsAdoulin=true },
["Silver Knife"]=                   {id=283,  IsTown=true ,  IsAdoulin=true },
["Celennia Memorial Library"]=      {id=284,  IsTown=true ,  IsAdoulin=true },
["Feretory"]=                       {id=285,  IsTown=false,  IsAdoulin=false},
["Maquette Abdhaljs-LegionB"]=      {id=287,  IsTown=false,  IsAdoulin=false},
["Escha - Zi'Tah"]=                 {id=288,  IsTown=false,  IsAdoulin=false},
["Escha - Ru'Aun"]=                 {id=289,  IsTown=false,  IsAdoulin=false},
["Desuetia - Empyreal Paradox"]=    {id=290,  IsTown=false,  IsAdoulin=false},
["Reisenjima"]=                     {id=291,  IsTown=false,  IsAdoulin=false},
["Reisenjima Henge"]=               {id=292,  IsTown=false,  IsAdoulin=false},
["Reisenjima Sanctorium"]=          {id=293,  IsTown=false,  IsAdoulin=false},
["Dynamis - San d'Oria [D]"]=       {id=294,  IsTown=false,  IsAdoulin=false},
["Dynamis - Bastok [D]"]=           {id=295,  IsTown=false,  IsAdoulin=false},
["Dynamis - Windurst [D]"]=         {id=296,  IsTown=false,  IsAdoulin=false},
["Dynamis - Jeuno [D]"]=            {id=297,  IsTown=false,  IsAdoulin=false},
["Walk of Echoes [P1]"]=            {id=298,  IsTown=false,  IsAdoulin=false},
["Gwora - Throne Room"]=            {id=299,  IsTown=false,  IsAdoulin=false}
}