require "YAGDRSL/events/custom/force_status_update.lua"
require "YAGDRSL/events/custom/on_chunk.lua"
require "YAGDRSL/events/custom/on_load.lua"
require "YAGDRSL/events/custom/on_logout.lua"
require "YAGDRSL/events/custom/on_tick.lua"
require "YAGDRSL/events/custom/on_zone.lua"

require "YAGDRSL/events/gearswap/aftercast.lua"
require "YAGDRSL/events/gearswap/buff_change.lua"
require "YAGDRSL/events/gearswap/buff_refresh.lua"
require "YAGDRSL/events/gearswap/file_unload.lua"
require "YAGDRSL/events/gearswap/filtered_action.lua"
require "YAGDRSL/events/gearswap/indi_change.lua"
require "YAGDRSL/events/gearswap/midcast.lua"
require "YAGDRSL/events/gearswap/party_buff_change.lua"
require "YAGDRSL/events/gearswap/pet_aftercast.lua"
require "YAGDRSL/events/gearswap/pet_change.lua"
require "YAGDRSL/events/gearswap/pet_midcast.lua"
require "YAGDRSL/events/gearswap/pet_status_change.lua"
require "YAGDRSL/events/gearswap/precast.lua"
require "YAGDRSL/events/gearswap/pretarget.lua"
require "YAGDRSL/events/gearswap/status_change.lua"
require "YAGDRSL/events/gearswap/sub_job_change.lua"

require "YAGDRSL/events/gearswap/commands/YAG_commands.lua"
require "YAGDRSL/events/gearswap/self_command.lua"