-- Names and states of custom resource maps built by the library.
MAP_BUFF_NAMES = "custom_map_buff_names"
MAP_BUFF_NAMES_POPULATED = false
MAP_EQUIPMENT_NAMES = "custom_map_equipment_names"
MAP_EQUIPMENT_NAMES_POPULATED = false

-- Names of static mapping tables included with the library.
MAP_JA = "custom_map_ja"
MAP_ELEMENT_OPPOSITES = "custom_map_elements"
MAP_SKILLCHAIN_ELEMENTS = "custom_map_skillchain_elements"
MAP_SKILLCHAIN_MESSAGES = "custom_map_skillchain_messages"
MAP_SKILLS = "custom_map_skills"
MAP_SPELLS = "custom_map_spells"
MAP_WS = "custom_map_ws"
MAP_ZONES = "custom_map_zones"

-- Names to represent broad splits in types of spells
MAP_CLASS_BLACK_MAGIC = "black"
MAP_CLASS_WHITE_MAGIC = "white"

-- Mapping values to describe damage types
MAP_DAMAGE_HYBRID = "hybrid"
MAP_DAMAGE_MAGICAL = "magical"
MAP_DAMAGE_PHYSICAL = "physical"
MAP_DAMAGE_NONE = "no_damage"

-- Enfeebling spell classes
MAP_ENFEEBLE_DURATION = "duration"
MAP_ENFEEBLE_POTENCY = "potency"

-- Mapping values to describe various attributes of game resources in the static mapping tables.
MAP_JA_DEFAULT = "ungrouped_ja"
MAP_JA_BLOODPACT = "bloodpact"
MAP_JA_BLOODPACT_RAGE = "rage"
MAP_JA_BLOODPACT_WARD = "ward"
MAP_JA_CORSAIRSHOT = "corsairshot"
MAP_JA_FLOURISH = "flourish"
MAP_JA_JIG = "jig"
MAP_JA_JUMP = "jump"
MAP_JA_MANEUVER = "maneuver"
MAP_JA_PET_READY = "petready"
MAP_JA_ROLL = "roll"
MAP_JA_RUNE = "rune"
MAP_JA_SAMBA = "samba"
MAP_JA_STEP = "step"
MAP_JA_WALTZ = "waltz"
MAP_JA_WALTZ_CURE = "cure"
MAP_JA_WALTZ_HEAL = "heal"

MAP_SKILL_AUTO_MELEE = "auto_melee"
MAP_SKILL_AUTO_ARCHERY = "auto_archery"
MAP_SKILL_AUTO_MAGIC = "auto_magic"
MAP_SKILL_DIVINE = "divine"
MAP_SKILL_HEALING = "healing"
MAP_SKILL_ENHANCING = "enhancing"
MAP_SKILL_ENFEEBLING = "enfeebling"
MAP_SKILL_ELEMENTAL = "elemental"
-- "darkmagic" instead of "dark" to not conflict with element "dark"
MAP_SKILL_DARK = "darkmagic"
MAP_SKILL_SUMMONING = "summoning"
MAP_SKILL_NINJUTSU = "ninjutsu"
MAP_SKILL_OTHER = "other"
MAP_SKILL_SINGING = "singing"
MAP_SKILL_STRINGED = "string_instrument"
MAP_SKILL_WIND = "wind_instrument"
MAP_SKILL_BLUE = "blue"
MAP_SKILL_GEOMANCY = "geomancy"
MAP_SKILL_HANDBELL = "handbell"

MAP_SPELL_DEFAULT = "ungrouped_spell"
MAP_SPELL_ABSORB = "absorb"
MAP_SPELL_ADDLE = "addle"
MAP_SPELL_ANCIENT = "ancient"
MAP_SPELL_ASPIR = "aspir"
MAP_SPELL_AVATAR = "avatar"
MAP_SPELL_BALLAD = "ballad"
MAP_SPELL_BANISH = "banish"
MAP_SPELL_BARELEMENT = "barelement"
MAP_SPELL_BARSTATUS = "barstatus"
MAP_SPELL_BIND = "bind"
MAP_SPELL_BIO = "bio"
MAP_SPELL_BLIND = "blind"
MAP_SPELL_BOOST = "boost"
MAP_SPELL_BREAK = "petrify"
MAP_SPELL_CAROL = "carol"
MAP_SPELL_CURAGA = "curaga"
MAP_SPELL_CURE = "cure"
MAP_SPELL_DIA = "dia"
MAP_SPELL_DISPEL = "dispel"
MAP_SPELL_DISTRACT = "distract"
MAP_SPELL_DRAIN = "drain"
MAP_SPELL_ELEMENTAL_DEBUFF = "debuff"
MAP_SPELL_ELEGY = "elegy"
MAP_SPELL_ENDARK = "endark"
MAP_SPELL_ENLIGHT = "enlight"
MAP_SPELL_ENSPELL1 = "enspell1"
MAP_SPELL_ENSPELL2 = "enspell2"
MAP_SPELL_ETUDE = "etude"
MAP_SPELL_FLURRY = "flurry"
MAP_SPELL_FRAZZLE = "frazzle"
MAP_SPELL_GAIN = "gain"
MAP_SPELL_GEO = "geo"
MAP_SPELL_GRAVITY = "gravity"
MAP_SPELL_HASTE = "haste"
MAP_SPELL_HELIX = "helix"
MAP_SPELL_HOLY = "holy"
MAP_SPELL_INDI = "indi"
MAP_SPELL_LULLABY = "lullaby"
MAP_SPELL_LULLABY_FOE = "foe"
MAP_SPELL_LULLABY_HORDE = "horde"
MAP_SPELL_MADRIGAL = "madrigal"
MAP_SPELL_MAMBO = "mambo"
MAP_SPELL_MARCH = "march"
MAP_SPELL_MAZURKA = "mazurka"
MAP_SPELL_MINNE = "minne"
MAP_SPELL_MINUET = "minuet"
MAP_SPELL_NINJUTSU_DEBUFF = "debuff"
MAP_SPELL_NINJUTSU_ELEMENTAL = "elemental"
MAP_SPELL_PAEON = "paeon"
MAP_SPELL_PARALYZE = "paralyze"
MAP_SPELL_PHALANX = "phalanx"
MAP_SPELL_POISON = "poison"
MAP_SPELL_PRELUDE = "prelude"
MAP_SPELL_PROTECT = "protect"
MAP_SPELL_RAISE = "raise"
MAP_SPELL_REFRESH = "refresh"
MAP_SPELL_REGEN = "regen"
MAP_SPELL_REQUIEM = "requiem"
MAP_SPELL_RERAISE = "reraise"
MAP_SPELL_SHELL = "shell"
MAP_SPELL_SILENCE = "silence"
MAP_SPELL_SLEEP = "sleep"
MAP_SPELL_SLOW = "slow"
MAP_SPELL_SPIKES = "spikes"
MAP_SPELL_SPIRIT = "spirit"
MAP_SPELL_STATUSREMOVAL = "statusremoval"
MAP_SPELL_STORM = "storm"
MAP_SPELL_TELEPORT = "teleport"
MAP_SPELL_TEMPER = "temper"
MAP_SPELL_THRENODY = "threnody"
MAP_SPELL_TRUST = "trust"
MAP_SPELL_UTSUSEMI = "utsusemi"
MAP_SPELL_WARP = "warp"

MAP_WS_MELEE = "melee"
MAP_WS_RANGED = "distant"