function DeclareMidcastSets()
	_G[SETS_ROOT_NAME][EVENT_MIDCAST] = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_ITEM] = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA] = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_BLOODPACT] = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_BLOODPACT][MAP_JA_BLOODPACT_RAGE]    = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_BLOODPACT][MAP_JA_BLOODPACT_RAGE][MAP_DAMAGE_HYBRID]    = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_BLOODPACT][MAP_JA_BLOODPACT_RAGE][MAP_DAMAGE_MAGICAL]   = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_BLOODPACT][MAP_JA_BLOODPACT_RAGE][MAP_DAMAGE_PHYSICAL]  = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_BLOODPACT][MAP_JA_BLOODPACT_WARD]    = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_BLOODPACT][MAP_JA_BLOODPACT_WARD][SPELL_TARGET_ENEMY]    = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_BLOODPACT][MAP_JA_BLOODPACT_WARD][SPELL_TARGET_FRIEND]   = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_CORSAIRSHOT]  = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_FLOURISH]     = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_JIG]          = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_JUMP]         = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_MANEUVER]     = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_READY]        = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_READY][MAP_DAMAGE_MAGICAL]        = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_READY][MAP_DAMAGE_PHYSICAL]       = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_ROLL]         = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_RUNE]         = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_SAMBA]        = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_STEP]         = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_WALTZ]        = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_WALTZ][MAP_JA_WALTZ_CURE]        = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_WALTZ][MAP_JA_WALTZ_HEAL]        = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC] = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_BLUE]                          = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_BLUE][MAP_DAMAGE_MAGICAL]      = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_BLUE][MAP_DAMAGE_PHYSICAL]      = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_BLUE][MAP_SPELL_CURE]          = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_BLUE][MAP_SKILL_ENFEEBLING]    = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_BLUE][MAP_SKILL_ENHANCING]     = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_BLUE][MAP_SPELL_REFRESH]       = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_BLUE][MAP_SPELL_REGEN]         = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DARK]                    = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DARK][MAP_SPELL_ABSORB]          = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DARK][MAP_SPELL_ASPIR]           = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DARK][MAP_SPELL_BIO]             = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DARK][MAP_SPELL_DRAIN]           = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DARK][MAP_SPELL_ENDARK]          = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DIVINE]                    = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DIVINE][MAP_SPELL_BANISH]          = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DIVINE][MAP_SPELL_ENLIGHT]         = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DIVINE][MAP_SPELL_HOLY]            = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING]                    = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_SPELL_ADDLE]           = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_SPELL_BIND]            = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_SPELL_BLIND]           = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_SPELL_BREAK]           = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_SPELL_DIA]             = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_SPELL_DISPEL]          = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_SPELL_DISTRACT]        = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_SPELL_FRAZZLE]         = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_SPELL_GRAVITY]         = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_SPELL_PARALYZE]        = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_SPELL_POISON]          = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_SPELL_SILENCE]         = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_SPELL_SLEEP]           = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_SPELL_SLOW]            = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING]                    = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_SPELL_BARELEMENT]      = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_SPELL_BARSTATUS]       = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_SPELL_BOOST]           = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_SPELL_ENSPELL]         = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_SPELL_FLURRY]          = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_SPELL_GAIN]            = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_SPELL_HASTE]           = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_SPELL_PHALANX]         = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_SPELL_PROTECT]         = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_SPELL_REGEN]           = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_SPELL_REFRESH]         = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_SPELL_SHELL]           = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_SPELL_SPIKES]          = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_SPELL_STORM]           = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_SPELL_TELEPORT]        = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_SPELL_TEMPER]          = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_SPELL_WARP]            = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ELEMENTAL]                    = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ELEMENTAL][MAP_SPELL_ANCIENT]       = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ELEMENTAL][MAP_SPELL_ELEMENTAL_DEBUFF]       = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ELEMENTAL][MAP_SPELL_HELIX]           = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_GEOMANCY]                    = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_GEOMANCY][MAP_SPELL_INDI]            = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_GEOMANCY][MAP_SPELL_GEO]             = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_HEALING]                    = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_HEALING][MAP_SPELL_CURE]            = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_HEALING][MAP_SPELL_CURAGA]          = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_HEALING][MAP_SPELL_RAISE]           = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_HEALING][MAP_SPELL_RERAISE]         = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_HEALING][MAP_SPELL_STATUSREMOVAL]   = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_NINJUTSU]                    = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_NINJUTSU][MAP_SPELL_NINJUTSU_DEBUFF]  = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_NINJUTSU][MAP_SPELL_NINJUTSU_ELEMENTAL] = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_NINJUTSU][MAP_SPELL_UTSUSEMI]        = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_OTHER]                    = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_OTHER][MAP_SPELL_TRUST]           = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING]                                            = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND]                       = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_BALLAD]     = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_CAROL]      = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_ETUDE]      = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_MADRIGAL]   = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_MAMBO]      = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_MARCH]      = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_MAZURKA]    = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_MINNE]      = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_MINUET]     = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_PAEON]      = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_PRELUDE]    = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_ENEMY]                        = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_ENEMY][MAP_SPELL_ELEGY]       = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_ENEMY][MAP_SPELL_LULLABY]     = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_ENEMY][MAP_SPELL_REQUIEM]     = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_ENEMY][MAP_SPELL_THRENODY]    = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SUMMONING]                    = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SUMMONING][MAP_SPELL_AVATAR]          = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SUMMONING][MAP_SPELL_SPIRIT]          = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_RA] = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS] = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS][MAP_WS_MELEE]             = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS][MAP_WS_MELEE][MAP_DAMAGE_HYBRID]   = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS][MAP_WS_MELEE][MAP_DAMAGE_MAGICAL]  = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS][MAP_WS_MELEE][MAP_DAMAGE_PHYSICAL] = {}

	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS][MAP_WS_RANGED]             = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS][MAP_WS_RANGED][MAP_DAMAGE_HYBRID]   = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS][MAP_WS_RANGED][MAP_DAMAGE_MAGICAL]  = {}
	_G[SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS][MAP_WS_RANGED][MAP_DAMAGE_PHYSICAL] = {}
end