function DeclareStatusSets()
	_G[SETS_ROOT_NAME][STATUS_ENGAGED] = {}

	_G[SETS_ROOT_NAME][STATUS_IDLE] = {}
	_G[SETS_ROOT_NAME][STATUS_IDLE][ZONE_FIELD] = {}
	_G[SETS_ROOT_NAME][STATUS_IDLE][ZONE_TOWN] = {}

	_G[SETS_ROOT_NAME][STATUS_RESTING] = {}
end