function DeclareValidationTables()
	_G[VALIDATION_ROOT_NAME] = {}
	_G[VALIDATION_ROOT_NAME][VALIDATION_CHARACTER_EQUIPMENT_IDS] = {}
	_G[VALIDATION_ROOT_NAME][VALIDATION_CHARACTER_EQUIPMENT_NAMES] = {}
	_G[VALIDATION_ROOT_NAME][VALIDATION_CHARACTER_EQUIPMENT_NOT_USED] = {}
	_G[VALIDATION_ROOT_NAME][VALIDATION_GEARSET_ITEMS] = {}
	_G[VALIDATION_ROOT_NAME][VALIDATION_GEARSET_ITEMS_NOT_FOUND] = {}
	_G[VALIDATION_ROOT_NAME][VALIDATION_GEARSET_IDS] = {}
	_G[VALIDATION_ROOT_NAME][VALIDATION_GEARSET_INVALID_NAMES] = {}
	_G[VALIDATION_ROOT_NAME][VALIDATION_GEARSET_INVALID_SLOTS] = {}
	_G[VALIDATION_ROOT_NAME][VALIDATION_GEARSET_UNDEFINED_AUGMENTS] = {}
end