-- Container objects the library will read to determine the order of mod application.

function DeclareModOrderTables()
	_G[MOD_ORDER_CONTAINER] = {}

	_G[MOD_ORDER_CONTAINER][MOD_ORDER_PRECAST_JA_OFFENSE] = {}
	_G[MOD_ORDER_CONTAINER][MOD_ORDER_PRECAST_JA_DEFENSE] = {}
	_G[MOD_ORDER_CONTAINER][MOD_ORDER_MIDCAST_JA_OFFENSE] = {}
	_G[MOD_ORDER_CONTAINER][MOD_ORDER_MIDCAST_JA_DEFENSE] = {}

	_G[MOD_ORDER_CONTAINER][MOD_ORDER_PRECAST_MAGIC_OFFENSE] = {}
	_G[MOD_ORDER_CONTAINER][MOD_ORDER_PRECAST_MAGIC_DEFENSE] = {}
	_G[MOD_ORDER_CONTAINER][MOD_ORDER_MIDCAST_MAGIC_OFFENSE] = {}
	_G[MOD_ORDER_CONTAINER][MOD_ORDER_MIDCAST_MAGIC_DEFENSE] = {}

	_G[MOD_ORDER_CONTAINER][MOD_ORDER_PRECAST_RA_OFFENSE] = {}
	_G[MOD_ORDER_CONTAINER][MOD_ORDER_PRECAST_RA_DEFENSE] = {}
	_G[MOD_ORDER_CONTAINER][MOD_ORDER_MIDCAST_RA_OFFENSE] = {}
	_G[MOD_ORDER_CONTAINER][MOD_ORDER_MIDCAST_RA_DEFENSE] = {}

	_G[MOD_ORDER_CONTAINER][MOD_ORDER_PRECAST_WS_OFFENSE] = {}
	_G[MOD_ORDER_CONTAINER][MOD_ORDER_PRECAST_WS_DEFENSE] = {}
	--_G[MOD_ORDER_CONTAINER][MOD_ORDER_MIDCAST_WS_OFFENSE] = {}
	--_G[MOD_ORDER_CONTAINER][MOD_ORDER_MIDCAST_WS_DEFENSE] = {}

	_G[MOD_ORDER_CONTAINER][MOD_ORDER_STATUS_ENGAGED_OFFENSE] = {}
	_G[MOD_ORDER_CONTAINER][MOD_ORDER_STATUS_ENGAGED_DEFENSE] = {}

	_G[MOD_ORDER_CONTAINER][MOD_ORDER_STATUS_IDLE_OFFENSE] = {}
	_G[MOD_ORDER_CONTAINER][MOD_ORDER_STATUS_IDLE_DEFENSE] = {}

	_G[MOD_ORDER_CONTAINER][MOD_ORDER_STATUS_RESTING_OFFENSE] = {}
	_G[MOD_ORDER_CONTAINER][MOD_ORDER_STATUS_RESTING_DEFENSE] = {}

	_G[MOD_ORDER_CONTROL_PANEL] = {}

	_G[MOD_ORDER_LIST_OFFENSE] =
		{
		MOD_ORDER_PRECAST_JA_OFFENSE,    MOD_ORDER_MIDCAST_JA_OFFENSE,
		MOD_ORDER_PRECAST_MAGIC_OFFENSE, MOD_ORDER_MIDCAST_MAGIC_OFFENSE,
		MOD_ORDER_PRECAST_RA_OFFENSE,    MOD_ORDER_MIDCAST_RA_OFFENSE,
		MOD_ORDER_PRECAST_WS_OFFENSE,    --MOD_ORDER_MIDCAST_WS_OFFENSE,

		MOD_ORDER_STATUS_ENGAGED_OFFENSE,
		MOD_ORDER_STATUS_IDLE_OFFENSE,
		MOD_ORDER_STATUS_RESTING_OFFENSE
		}

	_G[MOD_ORDER_LIST_DEFENSE] =
		{
		MOD_ORDER_PRECAST_JA_DEFENSE,    MOD_ORDER_MIDCAST_JA_DEFENSE,
		MOD_ORDER_PRECAST_MAGIC_DEFENSE, MOD_ORDER_MIDCAST_MAGIC_DEFENSE,
		MOD_ORDER_PRECAST_RA_DEFENSE,    MOD_ORDER_MIDCAST_RA_DEFENSE,
		MOD_ORDER_PRECAST_WS_DEFENSE,    --MOD_ORDER_MIDCAST_WS_DEFENSE,

		MOD_ORDER_STATUS_ENGAGED_DEFENSE,
		MOD_ORDER_STATUS_IDLE_DEFENSE,
		MOD_ORDER_STATUS_RESTING_DEFENSE
		}
end