function DeclareMidcastOverrides()
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST] = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_ITEM] = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA] = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_BLOODPACT] = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_BLOODPACT][MAP_JA_BLOODPACT_RAGE]    = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_BLOODPACT][MAP_JA_BLOODPACT_RAGE][MAP_DAMAGE_HYBRID]    = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_BLOODPACT][MAP_JA_BLOODPACT_RAGE][MAP_DAMAGE_MAGICAL]   = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_BLOODPACT][MAP_JA_BLOODPACT_RAGE][MAP_DAMAGE_PHYSICAL]  = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_BLOODPACT][MAP_JA_BLOODPACT_WARD]    = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_BLOODPACT][MAP_JA_BLOODPACT_WARD][SPELL_TARGET_ENEMY]    = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_BLOODPACT][MAP_JA_BLOODPACT_WARD][SPELL_TARGET_FRIEND]   = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_CORSAIRSHOT]  = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_FLOURISH]     = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_JIG]          = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_JUMP]         = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_MANEUVER]     = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_PET_READY]        = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_PET_READY][MAP_DAMAGE_MAGICAL]        = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_PET_READY][MAP_DAMAGE_PHYSICAL]       = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_ROLL]         = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_RUNE]         = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_SAMBA]        = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_STEP]         = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_WALTZ]        = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_WALTZ][MAP_JA_WALTZ_CURE]        = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_JA][MAP_JA_WALTZ][MAP_JA_WALTZ_HEAL]        = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC] = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_BLUE]                          = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_BLUE][MAP_DAMAGE_MAGICAL]      = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_BLUE][MAP_DAMAGE_PHYSICAL]      = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_BLUE][MAP_SPELL_CURE]          = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_BLUE][MAP_SKILL_ENFEEBLING]    = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_BLUE][MAP_SKILL_ENHANCING]     = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_BLUE][MAP_SPELL_REFRESH]       = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_BLUE][MAP_SPELL_REGEN]         = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DARK]                    = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DARK][MAP_SPELL_ABSORB]          = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DARK][MAP_SPELL_ASPIR]           = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DARK][MAP_SPELL_BIO]             = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DARK][MAP_SPELL_DRAIN]           = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DARK][MAP_SPELL_ENDARK]          = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DIVINE]                    = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DIVINE][MAP_SPELL_BANISH]          = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DIVINE][MAP_SPELL_ENLIGHT]         = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_DIVINE][MAP_SPELL_HOLY]            = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING]                                                   = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_CLASS_BLACK_MAGIC]                            = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_CLASS_BLACK_MAGIC][MAP_SPELL_DISPEL]          = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_CLASS_BLACK_MAGIC][MAP_ENFEEBLE_DURATION]     = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_CLASS_BLACK_MAGIC][MAP_SPELL_POISON]          = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_CLASS_BLACK_MAGIC][MAP_ENFEEBLE_POTENCY]      = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_CLASS_WHITE_MAGIC]                            = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_CLASS_WHITE_MAGIC][MAP_SPELL_DIA]             = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_CLASS_WHITE_MAGIC][MAP_ENFEEBLE_DURATION]     = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENFEEBLING][MAP_CLASS_WHITE_MAGIC][MAP_ENFEEBLE_POTENCY]      = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING]                                                   = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_BLACK_MAGIC]                            = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_BLACK_MAGIC][MAP_SPELL_SPIKES]          = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_BLACK_MAGIC][MAP_SPELL_WARP]            = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_WHITE_MAGIC]                            = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_WHITE_MAGIC][MAP_SPELL_BARELEMENT]      = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_WHITE_MAGIC][MAP_SPELL_BARSTATUS]       = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_WHITE_MAGIC][MAP_SPELL_BOOST]           = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_WHITE_MAGIC][MAP_SPELL_ENSPELL1]        = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_WHITE_MAGIC][MAP_SPELL_ENSPELL2]        = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_WHITE_MAGIC][MAP_SPELL_FLURRY]          = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_WHITE_MAGIC][MAP_SPELL_GAIN]            = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_WHITE_MAGIC][MAP_SPELL_HASTE]           = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_WHITE_MAGIC][MAP_SPELL_PHALANX]         = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_WHITE_MAGIC][MAP_SPELL_PROTECT]         = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_WHITE_MAGIC][MAP_SPELL_REGEN]           = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_WHITE_MAGIC][MAP_SPELL_REFRESH]         = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_WHITE_MAGIC][MAP_SPELL_SHELL]           = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_WHITE_MAGIC][MAP_SPELL_STORM]           = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_WHITE_MAGIC][MAP_SPELL_TELEPORT]        = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ENHANCING][MAP_CLASS_WHITE_MAGIC][MAP_SPELL_TEMPER]          = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ELEMENTAL]                    = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ELEMENTAL][MAP_SPELL_ANCIENT]       = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ELEMENTAL][MAP_SPELL_ELEMENTAL_DEBUFF]       = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_ELEMENTAL][MAP_SPELL_HELIX]           = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_GEOMANCY]                    = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_GEOMANCY][MAP_SPELL_INDI]            = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_GEOMANCY][MAP_SPELL_GEO]             = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_HEALING]                    = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_HEALING][MAP_SPELL_CURE]            = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_HEALING][MAP_SPELL_CURAGA]          = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_HEALING][MAP_SPELL_RAISE]           = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_HEALING][MAP_SPELL_RERAISE]         = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_HEALING][MAP_SPELL_STATUSREMOVAL]   = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_NINJUTSU]                    = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_NINJUTSU][MAP_SPELL_NINJUTSU_DEBUFF]  = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_NINJUTSU][MAP_SPELL_NINJUTSU_ELEMENTAL] = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_NINJUTSU][MAP_SPELL_UTSUSEMI]        = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_OTHER]                    = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_OTHER][MAP_SPELL_TRUST]           = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING]                                            = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND]                       = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_BALLAD]     = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_CAROL]      = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_ETUDE]      = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_MADRIGAL]   = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_MAMBO]      = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_MARCH]      = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_MAZURKA]    = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_MINNE]      = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_MINUET]     = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_PAEON]      = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_FRIEND][MAP_SPELL_PRELUDE]    = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_ENEMY]                        = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_ENEMY][MAP_SPELL_ELEGY]       = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_ENEMY][MAP_SPELL_LULLABY]     = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_ENEMY][MAP_SPELL_LULLABY][MAP_SPELL_LULLABY_FOE]     = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_ENEMY][MAP_SPELL_LULLABY][MAP_SPELL_LULLABY_HORDE]   = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_ENEMY][MAP_SPELL_REQUIEM]     = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SINGING][SPELL_TARGET_ENEMY][MAP_SPELL_THRENODY]    = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SUMMONING]                    = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SUMMONING][MAP_SPELL_AVATAR]          = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_MAGIC][MAP_SKILL_SUMMONING][MAP_SPELL_SPIRIT]          = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_RA] = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS] = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS][MAP_WS_MELEE]             = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS][MAP_WS_MELEE][MAP_DAMAGE_HYBRID]   = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS][MAP_WS_MELEE][MAP_DAMAGE_MAGICAL]  = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS][MAP_WS_MELEE][MAP_DAMAGE_PHYSICAL] = {}

	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS][MAP_WS_RANGED]             = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS][MAP_WS_RANGED][MAP_DAMAGE_HYBRID]   = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS][MAP_WS_RANGED][MAP_DAMAGE_MAGICAL]  = {}
	_G[OVERRIDE_SETS_ROOT_NAME][EVENT_MIDCAST][CATEGORY_WS][MAP_WS_RANGED][MAP_DAMAGE_PHYSICAL] = {}
end