function DeclareStatusMods()
	_G[MOD_SETS_ROOT_NAME][STATUS_CLASS] = {}
	_G[MOD_SETS_ROOT_NAME][STATUS_CLASS][STATUS_ENGAGED] = {}

	_G[MOD_SETS_ROOT_NAME][STATUS_CLASS][STATUS_IDLE] = {}
	_G[MOD_SETS_ROOT_NAME][STATUS_CLASS][STATUS_IDLE][ZONE_FIELD] = {}
	_G[MOD_SETS_ROOT_NAME][STATUS_CLASS][STATUS_IDLE][ZONE_TOWN] = {}

	_G[MOD_SETS_ROOT_NAME][STATUS_CLASS][STATUS_RESTING] = {}
end