function MakeBackupTables()
	BACKUP_ROOT = "backup_root"

	_G[BACKUP_ROOT] = {}
	_G[BACKUP_ROOT][MOD_SETS_ROOT_NAME]      = _G[MOD_SETS_ROOT_NAME]
	_G[BACKUP_ROOT][OVERRIDE_SETS_ROOT_NAME] = _G[OVERRIDE_SETS_ROOT_NAME]
	_G[BACKUP_ROOT][SETS_ROOT_NAME]          = _G[SETS_ROOT_NAME]
	_G[BACKUP_ROOT][MOD_ORDER_CONTAINER]     = _G[MOD_ORDER_CONTAINER]
	_G[BACKUP_ROOT][MOD_VALUES_ROOT_NAME]    = _G[MOD_VALUES_ROOT_NAME]

end

function RestoreBackupTables()
	_G[MOD_SETS_ROOT_NAME]      = _G[BACKUP_ROOT][MOD_SETS_ROOT_NAME]
	_G[OVERRIDE_SETS_ROOT_NAME] = _G[BACKUP_ROOT][OVERRIDE_SETS_ROOT_NAME]
	_G[SETS_ROOT_NAME]          = _G[BACKUP_ROOT][SETS_ROOT_NAME]
	_G[MOD_ORDER_CONTAINER]     = _G[BACKUP_ROOT][MOD_ORDER_CONTAINER]
	_G[MOD_VALUES_ROOT_NAME]    = _G[BACKUP_ROOT][MOD_VALUES_ROOT_NAME]
end